CFG_Set – Quest
CFG_Set Interface
5 statements
Source File
public interface CFG_Set
Calls
Called by
Module Procedures
public subroutine DQMC_Config_SetI(cfg, name, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(inout) :: cfg
character(len=*), intent(in) :: name
integer, intent(in) :: value
public subroutine DQMC_Config_SetR(cfg, name, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(inout) :: cfg
character(len=*), intent(in) :: name
real(kind=wp), intent(in) :: value
public subroutine DQMC_Config_SetS(cfg, name, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(inout) :: cfg
character(len=*), intent(in) :: name
character(len=*), intent(in) :: value
public subroutine DQMC_Config_SetPR(cfg, name, n, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(inout) :: cfg
character(len=*), intent(in) :: name
integer, intent(in) :: n
real(kind=wp), intent(in) :: value(n)
public subroutine DQMC_Config_SetPI(cfg, name, n, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(inout) :: cfg
character(len=*), intent(in) :: name
integer, intent(in) :: n
integer, intent(in) :: value(n)
Call graph
cfg_set calls dqmc_config_seti, dqmc_config_setpi, dqmc_config_setpr, dqmc_config_setr, dqmc_config_sets
dqmc_config_seti calls dqmc_error, dqmc_find_param
dqmc_config_setpi calls dqmc_error, dqmc_find_param
dqmc_config_setpr calls dqmc_error, dqmc_find_param
dqmc_config_setr calls dqmc_error, dqmc_find_param
dqmc_config_sets calls dqmc_error, dqmc_find_param
dqmc_geom_init calls cfg_set
dqmc_hub_config calls cfg_set
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_geom_init, dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl