CFG_Get – Quest
CFG_Get Interface
5 statements
Source File
public interface CFG_Get
Calls
Called by
Module Procedures
public subroutine DQMC_Config_GetI(cfg, name, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(in) :: cfg
character(len=*), intent(in) :: name
integer, intent(out) :: value
public subroutine DQMC_Config_GetR(cfg, name, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(in) :: cfg
character(len=*), intent(in) :: name
real(kind=wp), intent(out) :: value
public subroutine DQMC_Config_GetS(cfg, name, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(in) :: cfg
character(len=*), intent(in) :: name
character(len=slen) :: value
public subroutine DQMC_Config_GetPR(cfg, name, n, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(in) :: cfg
character(len=*), intent(in) :: name
integer, intent(out) :: n
real(kind=wp), intent(inout), pointer :: value(:)
public subroutine DQMC_Config_GetPI(cfg, name, n, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(in) :: cfg
character(len=*), intent(in) :: name
integer, intent(out) :: n
integer, intent(inout), pointer :: value(:)
Call graph
cfg_get calls dqmc_config_geti, dqmc_config_getpi, dqmc_config_getpr, dqmc_config_getr, dqmc_config_gets
dqmc_config_geti calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpi calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_gets calls dqmc_error, dqmc_find_param, dqmc_warning
construct_hamilt calls cfg_get
dqmc_comp_2dperl calls cfg_get, dqmc_hub_config
dqmc_hub_config calls cfg_get
init_recip_latt calls cfg_get
dqmc_ggeom calls cfg_get, dqmc_hub_config, dqmc_geom_fill
dqmc_geom_fill calls construct_hamilt, init_recip_latt
dqmc_test calls dqmc_comp_2dperl