DQMC_Phy2_GetIrrep – Quest
DQMC_Phy2_GetIrrep Interface
3 statements
Source File
public interface DQMC_Phy2_GetIrrep
Calls
Called by
Module Procedures
public subroutine DQMC_Phy2_GetIrrep_Connected(P2, G_fun, S)
Arguments
Type Intent Optional Attributes Name
type(Phy2), intent(inout) :: P2
real(kind=wp), intent(in) :: G_fun(S%nclass)
type(Struct), intent(inout) :: S
public subroutine DQMC_Phy2_GetIrrep_Full(P2, S)
Arguments
Type Intent Optional Attributes Name
type(Phy2), intent(inout) :: P2
type(Struct), intent(inout) :: S
Call graph
dqmc_phy2_getirrep calls dqmc_phy2_getirrep_connected, dqmc_phy2_getirrep_full
dqmc_phy2_getirrep_connected calls lapack_dsyev, dqmc_phy2_pair
dqmc_phy2_getirrep_full calls lapack_dsyev
dqmc_ggeom calls dqmc_phy2_getirrep