DQMC_Print_Array – Quest
DQMC_Print_Array Interface
3 statements
Source File
public interface DQMC_Print_Array
Calls
Called by
Module Procedures
public subroutine DQMC_Print_RealArray(n, m, title, label, avg, err, OPT)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in) :: title
character(len=*), intent(in) :: label(:)
real(kind=wp), intent(in) :: avg(:,:)
real(kind=wp), intent(in) :: err(:,:)
integer, intent(in) :: OPT
public subroutine DQMC_Print_ComplexArray(n, m, title, label, avg, err, OPT)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in) :: title
character(len=*), intent(in) :: label(:)
complex(kind=wp), intent(in) :: avg(:,:)
complex(kind=wp), intent(in) :: err(:,:)
integer, intent(in) :: OPT
Call graph
dqmc_print_array calls dqmc_print_complexarray, dqmc_print_realarray
dqmc_tdm1_print calls dqmc_print_array
dqmc_tdm1_printkft calls dqmc_print_array
dqmc_tdm1_selfenergy calls dqmc_print_array
dqmc_ggeom calls dqmc_tdm1_print, dqmc_tdm1_printkft, dqmc_tdm1_selfenergy