construct_hamilt – Quest
construct_hamilt Subroutine
107 statements
Source File
public subroutine construct_hamilt(hamilt, lattice, recip_lattice, cfg)
Arguments
Type Intent Optional Attributes Name
type(Hamiltonian_t), intent(out) :: hamilt
type(lattice_t), intent(in), target :: lattice
type(recip_lattice_t), intent(in) :: recip_lattice
type(config), intent(inout) :: cfg
Calls
Called by
Call graph
construct_hamilt calls cfg_get, dqmc_hamilt_groupckb, find_neighbors, hoptowho, move_to_record
cfg_get calls dqmc_config_geti, dqmc_config_getpi, dqmc_config_getpr, dqmc_config_getr, dqmc_config_gets
hoptowho calls get_inverse
dqmc_config_geti calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpi calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_gets calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_geom_fill calls construct_hamilt
dqmc_ggeom calls dqmc_geom_fill