convert_to_fractional – Quest
convert_to_fractional Subroutine
10 statements
Source File
public subroutine convert_to_fractional(xat, ainv)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(inout) :: xat(rdim)
real(kind=8), intent(in) :: ainv(rdim,rdim)
Called by
Call graph
assign_phase calls convert_to_fractional
init_lattice calls convert_to_fractional
dqmc_geom_fill calls assign_phase, init_lattice
dqmc_ggeom calls dqmc_geom_fill