DQMC_GFun_Clone – Quest
DQMC_GFun_Clone Subroutine
13 statements
Source File
public subroutine DQMC_GFun_Clone(G1, G2)
Arguments
Type Intent Optional Attributes Name
type(G_fun), intent(inout) :: G1
type(G_fun), intent(in) :: G2
Called by
Call graph
dqmc_hub_fullmeas calls dqmc_gfun_clone
dqmc_hub_init calls dqmc_gfun_clone
dqmc_hub_meas calls dqmc_gfun_clone
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_ggeom calls dqmc_hub_fullmeas, dqmc_hub_meas, dqmc_hub_config
dqmc_verify calls dqmc_hub_init
dqmc_test calls dqmc_comp_2dperl