DQMC_change_gtau_time – Quest
DQMC_change_gtau_time Subroutine
145 statements
Source File
public subroutine DQMC_change_gtau_time(tau, idir, spin)
Arguments
Type Intent Optional Attributes Name
type(Gtau), intent(inout) :: tau
integer, intent(in) :: idir
integer, intent(in) :: spin
Calls
Called by
Call graph
dqmc_change_gtau_time calls dqmc_gtau_setalias, dqmc_multb_left, dqmc_multb_right, dqmc_multbi_left, dqmc_multbi_right
dqmc_multb_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerow
dqmc_multb_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecol
dqmc_multbi_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerowinv
dqmc_multbi_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecolinv
dqmc_scalecol calls dscal
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_scalerowinv calls dscal
dqmc_makegtau calls dqmc_change_gtau_time
dqmc_tdm1_meas calls dqmc_change_gtau_time
dqmc_tdm1_meas_para calls dqmc_change_gtau_time
dqmc_ggeom calls dqmc_tdm1_meas, dqmc_tdm1_meas_para