DQMC_MultBi_Left – Quest
DQMC_MultBi_Left Subroutine
34 statements
Source File
public subroutine DQMC_MultBi_Left(n, M, B, V_i, C)
Check error message
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout) :: M(n,n)
type(matB), intent(in) :: B
real(kind=wp), intent(in) :: V_i(n)
real(kind=wp), intent(inout) :: C(n,n)
Calls
Called by
Call graph
dqmc_multbi_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerowinv
dqmc_scalerowinv calls dscal
dqmc_change_gtau_time calls dqmc_multbi_left
dqmc_seqmultbi calls dqmc_multbi_left
dqmc_getgtau calls dqmc_seqmultbi
dqmc_makegtau calls dqmc_change_gtau_time, dqmc_getgtau
dqmc_tdm1_meas calls dqmc_change_gtau_time
dqmc_tdm1_meas_para calls dqmc_change_gtau_time
dqmc_ggeom calls dqmc_tdm1_meas, dqmc_tdm1_meas_para