DQMC_Hub_Init – Quest
DQMC_Hub_Init Subroutine
178 statements
Source File
public subroutine DQMC_Hub_Init(Hub, U, t_up, t_dn, mu_up, mu_dn, L, n_t, n_U, n_mu, dtau, HSF_IPT, nWarm, nPass, nMeas, nTry, nBin, ntausk, seed, nOrth, nWrap, fixw, errrate, difflim, gamma, accept, reject, delta1, delta2, ssxx, HSFtype)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout) :: Hub
real(kind=wp), intent(in) :: U(:)
real(kind=wp), intent(in) :: t_up(:)
real(kind=wp), intent(in) :: t_dn(:)
real(kind=wp), intent(in) :: mu_up(:)
real(kind=wp), intent(in) :: mu_dn(:)
integer, intent(in) :: L
integer, intent(in) :: n_t
integer, intent(in) :: n_U
integer, intent(in) :: n_mu
real(kind=wp), intent(in) :: dtau
integer, intent(in) :: HSF_IPT
integer, intent(in) :: nWarm
integer, intent(in) :: nPass
integer, intent(in) :: nMeas
integer, intent(in) :: nTry
integer, intent(in) :: nBin
integer, intent(in) :: ntausk
integer, intent(in) :: seed
integer, intent(in) :: nOrth
integer, intent(in) :: nWrap
integer, intent(in) :: fixw
real(kind=wp), intent(in) :: errrate
real(kind=wp), intent(in) :: difflim
real(kind=wp), intent(in) :: gamma
integer, intent(in) :: accept
integer, intent(in) :: reject
real(kind=wp), intent(in) :: delta1
real(kind=wp), intent(in) :: delta2
integer, intent(in) :: ssxx
integer, intent(in) :: HSFtype
Calls
Called by
Call graph
dqmc_hub_init calls dqmc_b_init, dqmc_error, dqmc_getg, dqmc_gfun_clone, dqmc_gfun_init, dqmc_hub_init_vmat, dqmc_hub_input_hsf, dqmc_phy0_init, dqmc_phy2_init, dqmc_seqb_init, dqmc_warning, dqmc_wspace_allocate, ran0, ran1
dqmc_b_init calls dqmc_b_expinit
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
dqmc_hub_input_hsf calls dqmc_error
dqmc_wspace_allocate calls lapack_dgeqp3, lapack_dgetri, lapack_dorgqr, lapack_dormqr, lapack_dsyev
ran0 calls dlarnv
ran1 calls dlarnv
dqmc_b_expinit calls dqmc_error, lapack_dsyev, blas_dgemm, blas_dscal, dexp
dqmc_computeg calls dqmc_error, dqmc_warning, blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_scalerow, dqmc_seqmultb, dqmc_trans
dqmc_multb_left calls dqmc_error, lapack_dsyev, blas_dgemm, blas_dscal, dexp, dqmc_scalerow
dqmc_multbi_right calls dqmc_error, lapack_dsyev, blas_dgemm, blas_dscal, dexp, dqmc_scalecolinv
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_multb_left, dqmc_eye, dqmc_getb, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_udtd calls dqmc_error, blas_dcopy, lapack_dgeqp3, lapack_dorgqr, blas_dscal, blas_dtrmm, dqmc_scalecol
dqmc_multb_right calls dqmc_error, lapack_dsyev, blas_dgemm, blas_dscal, dexp, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_hub_config calls dqmc_hub_init
dqmc_verify calls dqmc_hub_init
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl