DQMC_Hub_Sweep_Cont – Quest
DQMC_Hub_Sweep_Cont Subroutine
137 statements
Source File
public subroutine DQMC_Hub_Sweep_Cont(Hub, nMeas0)
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout), target :: Hub
integer, intent(in) :: nMeas0
Calls
Call graph
dqmc_hub_sweep_cont calls dqmc_applyupdate, dqmc_getg, dqmc_gfun_getjj, dqmc_phy0_meas, dqmc_phy2_meas, dqmc_updateg, dqmc_updatewraps, ran0
dqmc_applyupdate calls blas_dgemm
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
dqmc_gfun_getjj calls blas_ddot
dqmc_phy0_meas calls blas_daxpy, blas_dgemm
dqmc_phy2_meas calls blas_daxpy, dqmc_phy2_pair
dqmc_updateg calls dqmc_applyupdate, blas_dgemv, blas_dscal
ran0 calls dlarnv
dqmc_computeg calls blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_error, dqmc_scalerow, dqmc_seqmultb, dqmc_trans, dqmc_warning
dqmc_multb_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerow
dqmc_multbi_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecolinv
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_multb_left, dqmc_eye, dqmc_getb, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_udtd calls blas_dcopy, blas_dscal, dqmc_error, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_scalecol
dqmc_multb_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecol
dqmc_scalecol calls dscal