DQMC_Gtau_DumpA – Quest
DQMC_Gtau_DumpA Subroutine
28 statements
Source File
public subroutine DQMC_Gtau_DumpA(tau, spin, it, i0)
Arguments
Type Intent Optional Attributes Name
type(Gtau), intent(inout) :: tau
integer, intent(in) :: spin
integer, intent(in) :: it
integer, intent(in) :: i0
Calls
Called by
Call graph
dqmc_gtau_dumpa calls dqmc_gtau_setalias
dqmc_tdm1_meas calls dqmc_gtau_dumpa
dqmc_tdm1_meas_para calls dqmc_gtau_dumpa
dqmc_ggeom calls dqmc_tdm1_meas, dqmc_tdm1_meas_para