DQMC_Geom_Init – Quest
DQMC_Geom_Init Subroutine
93 statements
Source File
public subroutine DQMC_Geom_Init(gwrap, S, cfg)
Arguments
Type Intent Optional Attributes Name
type(GeomWrap), intent(in) :: gwrap
type(Struct), intent(inout) :: S
type(config), intent(inout) :: cfg
Calls
Called by
Call graph
dqmc_geom_init calls cfg_set, dqmc_ccs_compress, group_hopping
cfg_set calls dqmc_config_seti, dqmc_config_setpi, dqmc_config_setpr, dqmc_config_setr, dqmc_config_sets
dqmc_ccs_compress calls dqmc_error
dqmc_config_seti calls dqmc_error, dqmc_find_param
dqmc_config_setpi calls dqmc_error, dqmc_find_param
dqmc_config_setpr calls dqmc_error, dqmc_find_param
dqmc_config_setr calls dqmc_error, dqmc_find_param
dqmc_config_sets calls dqmc_error, dqmc_find_param
dqmc_ggeom calls dqmc_geom_init