DQMC_UpdateG – Quest
DQMC_UpdateG Subroutine
25 statements
Source File
public subroutine DQMC_UpdateG(j, gamma, G)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j
real(kind=wp), intent(in) :: gamma
type(G_fun), intent(inout), target :: G
Calls
Called by
Call graph
dqmc_updateg calls blas_dgemv, blas_dscal, dqmc_applyupdate
dqmc_applyupdate calls blas_dgemm
dqmc_hub_sweep calls dqmc_updateg
dqmc_hub_sweep_cont calls dqmc_updateg
dqmc_comp_2dperl calls dqmc_hub_sweep
dqmc_hub_run calls dqmc_hub_sweep
dqmc_ggeom calls dqmc_hub_sweep
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run