DQMC_MatDiff – Quest
DQMC_MatDiff Function
12 statements
Source File
public function DQMC_MatDiff(n, A, B) result(diff)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=WP), intent(in) :: A(n,n)
real(kind=WP), intent(in) :: B(n,n)
Return Value real(kind=WP)
Called by
Call graph
dqmc_getg calls dqmc_matdiff
dqmc_hub_init calls dqmc_getg
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_ggeom calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_verify calls dqmc_hub_init, dqmc_hub_run
dqmc_test calls dqmc_comp_2dperl