DQMC_Config_SetPR – Quest
DQMC_Config_SetPR Subroutine
19 statements
Source File
public subroutine DQMC_Config_SetPR(cfg, name, n, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(inout) :: cfg
character(len=*), intent(in) :: name
integer, intent(in) :: n
real(kind=wp), intent(in) :: value(n)
Calls
Called by
Call graph
dqmc_config_setpr calls dqmc_error, dqmc_find_param
cfg_set calls dqmc_config_setpr
dqmc_geom_init calls cfg_set
dqmc_hub_config calls cfg_set
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_geom_init, dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl