DQMC_TDM1_Meas_Para – Quest
DQMC_TDM1_Meas_Para Subroutine
76 statements
Source File
public subroutine DQMC_TDM1_Meas_Para(t1, pT1, tau, ptau)
Arguments
Type Intent Optional Attributes Name
type(TDM1), intent(inout) :: t1
type(TDM1), intent(inout) :: pT1(:)
type(Gtau), intent(inout) :: tau
type(Gtau), intent(inout) :: ptau(:)
Calls
Called by
Call graph
dqmc_tdm1_meas_para calls dqmc_change_gtau_time, dqmc_gtau_copyup, dqmc_gtau_dumpa, dqmc_tdm1_compute
dqmc_change_gtau_time calls dqmc_gtau_setalias, dqmc_multb_left, dqmc_multb_right, dqmc_multbi_left, dqmc_multbi_right
dqmc_gtau_dumpa calls dqmc_gtau_setalias
dqmc_multb_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerow
dqmc_multb_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecol
dqmc_multbi_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerowinv
dqmc_multbi_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecolinv
dqmc_scalecol calls dscal
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_scalerowinv calls dscal
dqmc_ggeom calls dqmc_tdm1_meas_para