DQMC_TDM1_PrintKFT – Quest
DQMC_TDM1_PrintKFT Subroutine
36 statements
Source File
public subroutine DQMC_TDM1_PrintKFT(T1, OPT)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(TDM1), intent(in) :: T1
integer, intent(in) :: OPT
Calls
Called by
Call graph
dqmc_tdm1_printkft calls dqmc_print_array
dqmc_print_array calls dqmc_print_complexarray, dqmc_print_realarray
dqmc_ggeom calls dqmc_tdm1_printkft