DQMC_B_Init – Quest
DQMC_B_Init Subroutine
37 statements
Source File
public subroutine DQMC_B_Init(n, B, WS, adj, ckb, t, mu, dtau)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(matB), intent(inout) :: B
type(WSpace), intent(inout), target :: WS
type(CCS), intent(in) :: adj
type(CCS), intent(out) :: ckb
real(kind=wp), intent(in) :: t(:)
real(kind=wp), intent(in) :: mu(n)
real(kind=wp), intent(in) :: dtau
Calls
Called by
Call graph
dqmc_b_init calls dqmc_b_expinit
dqmc_b_expinit calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error
dqmc_hub_init calls dqmc_b_init
dqmc_hub_config calls dqmc_hub_init
dqmc_verify calls dqmc_hub_init
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl