DQMC_Geom_Read_Def – Quest
DQMC_Geom_Read_Def Subroutine
238 statements
Source File
public subroutine DQMC_Geom_Read_Def(S, gfile, tableFormat)
Arguments
Type Intent Optional Attributes Name
type(Struct), intent(inout) :: S
character(len=*), intent(in) :: gfile
logical, intent(out) :: tableFormat
Calls
Called by
Call graph
dqmc_geom_read_def calls dqmc_ccs_compress, dqmc_error, dqmc_geom_discover_f, dqmc_geom_discover_map, dqmc_readln, dqmc_warning
dqmc_ccs_compress calls dqmc_error
dqmc_ggeom calls dqmc_geom_read_def