DQMC_Gtau_LoadA – Quest
DQMC_Gtau_LoadA Subroutine
67 statements
Source File
public subroutine DQMC_Gtau_LoadA(tau, spin, slice, sgn)
Arguments
Type Intent Optional Attributes Name
type(Gtau), intent(inout), target :: tau
integer, intent(in) :: spin
integer, intent(in) :: slice
real(kind=wp), intent(out) :: sgn
Calls
Called by
Call graph
dqmc_gtau_loada calls lapack_dgetrf, lapack_dgetri, dqmc_getb, dqmc_gtau_setalias, dqmc_multb_right
dqmc_getb calls dqmc_multb_right, dqmc_scalerow
dqmc_multb_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_scalerow calls dscal
dqmc_ggeom calls dqmc_gtau_loada