DQMC_Phy2_Pair – Quest
DQMC_Phy2_Pair Subroutine
28 statements
Source File
public subroutine DQMC_Phy2_Pair(n, M, up, dn, Bond)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout) :: M(:,:)
real(kind=wp), intent(in) :: up(:,:)
real(kind=wp), intent(in) :: dn(:,:)
type(CCS), intent(in) :: Bond
Called by
Call graph
dqmc_phy2_geterrirrep calls dqmc_phy2_pair
dqmc_phy2_getirrep_connected calls dqmc_phy2_pair
dqmc_phy2_meas calls dqmc_phy2_pair
dqmc_tdm2_meas calls dqmc_phy2_pair
dqmc_phy2_getirrep calls dqmc_phy2_getirrep_connected
dqmc_hub_fullmeas calls dqmc_phy2_meas
dqmc_hub_meas calls dqmc_phy2_meas
dqmc_hub_sweep calls dqmc_phy2_meas
dqmc_hub_sweep_cont calls dqmc_phy2_meas
dqmc_ggeom calls dqmc_phy2_geterrirrep, dqmc_phy2_getirrep, dqmc_hub_fullmeas, dqmc_hub_meas, dqmc_hub_sweep
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep
dqmc_hub_run calls dqmc_hub_sweep
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run