DQMC_Trans – Quest
DQMC_Trans Subroutine
6 statements
Source File
public subroutine DQMC_Trans(n, At, A)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout) :: At(n,n)
real(kind=wp), intent(in) :: A(n,n)
Called by
Call graph
dqmc_computeg calls dqmc_trans
dqmc_getgtau calls dqmc_trans
dqmc_multb_left calls dqmc_trans
dqmc_multbi_left calls dqmc_trans
dqmc_getbi calls dqmc_multbi_left
dqmc_getb calls dqmc_multb_left
dqmc_getg calls dqmc_computeg
dqmc_hol_sweep3_cont calls dqmc_computeg
dqmc_hub_sweep2_cont calls dqmc_computeg
dqmc_makegtau calls dqmc_getgtau
dqmc_hub_init calls dqmc_getg
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_ggeom calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_verify calls dqmc_hub_init, dqmc_hub_run
dqmc_test calls dqmc_comp_2dperl