DQMC_Gtau_GetG0 – Quest
DQMC_Gtau_GetG0 Subroutine
43 statements
Source File
public subroutine DQMC_Gtau_GetG0(n, tau, spin, slice, g0tau)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(Gtau), intent(inout) :: tau
integer, intent(in) :: spin
integer, intent(in) :: slice
real(kind=wp), intent(out) :: g0tau(n,n)
Calls
Called by
Call graph
dqmc_gtau_getg0 calls dcopy, dgemm, dsyev, dqmc_getb, dqmc_scalecol
dqmc_getb calls dqmc_multb_right, dqmc_scalerow
dqmc_scalecol calls dscal
dqmc_multb_right calls dqmc_scalecol, blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error
dqmc_scalerow calls dscal
dqmc_tdm1_selfenergy calls dqmc_gtau_getg0
dqmc_ggeom calls dqmc_tdm1_selfenergy