DQMC_TDM2_Avg – Quest
DQMC_TDM2_Avg Subroutine
34 statements
Source File
public subroutine DQMC_TDM2_Avg(T2, gnl, idx, factor)
Arguments
Type Intent Optional Attributes Name
type(TDM2), intent(inout) :: T2
real(kind=wp), intent(in) :: gnl(:,:)
integer, intent(in) :: idx
real(kind=wp), intent(in) :: factor
Calls
Call graph
dqmc_tdm2_avg calls dqmc_wave_avg
dqmc_wave_avg calls blas_ddot, blas_dgemm