DQMC_Read_Def – Quest
DQMC_Read_Def Subroutine
73 statements
Source File
public subroutine DQMC_Read_Def(cfg, IPT)
\brief Reads in parameters from a .def input file to a config (cfg) data type. \param[inout] cfg (\p config) config data type to store read in parameters to. \param[in] IPT (\p integer) unit number of opened .def input file.
Arguments
Type Intent Optional Attributes Name
type(config), intent(inout) :: cfg
integer, intent(in) :: IPT
Calls
Called by
Call graph
dqmc_read_def calls dqmc_readln
dqmc_read_config calls dqmc_read_def
dqmc_comp_2dperl calls dqmc_read_config
dqmc_ggeom calls dqmc_read_config
dqmc_test calls dqmc_comp_2dperl