DQMC_CCS_Compress – Quest
DQMC_CCS_Compress Subroutine
38 statements
Source File
public subroutine DQMC_CCS_Compress(n, nnz, A, sparA)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: nnz
integer, intent(in) :: A(:,:)
type(CCS), intent(inout) :: sparA
Calls
Called by
Call graph
dqmc_ccs_compress calls dqmc_error
dqmc_geom_init calls dqmc_ccs_compress
dqmc_geom_read_def calls dqmc_ccs_compress
dqmc_init_2dperl calls dqmc_ccs_compress
dqmc_comp_2dperl calls dqmc_init_2dperl
dqmc_ggeom calls dqmc_geom_init, dqmc_geom_read_def
dqmc_verify calls dqmc_init_2dperl
dqmc_test calls dqmc_comp_2dperl