DQMC_GetBi – Quest
DQMC_GetBi Subroutine
19 statements
Source File
public subroutine DQMC_GetBi(n, M, B, V_i, C)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout) :: M(n,n)
type(matB), intent(in) :: B
real(kind=wp), intent(in) :: V_i(n)
real(kind=wp), intent(inout) :: C(n,n)
Calls
Called by
Call graph
dqmc_getbi calls dqmc_multbi_right, dqmc_scalecolinv
dqmc_multbi_right calls dqmc_scalecolinv, blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error
dqmc_scalecolinv calls dscal
dqmc_seqmultbi calls dqmc_getbi
dqmc_getgtau calls dqmc_seqmultbi
dqmc_makegtau calls dqmc_getgtau