DQMC_Config_GetPR – Quest
DQMC_Config_GetPR Subroutine
28 statements
Source File
public subroutine DQMC_Config_GetPR(cfg, name, n, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(in) :: cfg
character(len=*), intent(in) :: name
integer, intent(out) :: n
real(kind=wp), intent(inout), pointer :: value(:)
Calls
Called by
Call graph
dqmc_config_getpr calls dqmc_error, dqmc_find_param, dqmc_warning
cfg_get calls dqmc_config_getpr
construct_hamilt calls cfg_get
dqmc_comp_2dperl calls cfg_get, dqmc_hub_config
dqmc_hub_config calls cfg_get
init_recip_latt calls cfg_get
dqmc_ggeom calls cfg_get, dqmc_hub_config, dqmc_geom_fill
dqmc_geom_fill calls construct_hamilt, init_recip_latt
dqmc_test calls dqmc_comp_2dperl