DQMC_Hub_Input_HSF – Quest
DQMC_Hub_Input_HSF Subroutine
47 statements
Source File
public subroutine DQMC_Hub_Input_HSF(Hub, restore, slice, IPT)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout) :: Hub
logical, intent(in) :: restore
integer, intent(out) :: slice
integer, intent(in) :: IPT
Calls
Called by
Call graph
dqmc_hub_input_hsf calls dqmc_error
dqmc_hub_init calls dqmc_hub_input_hsf
dqmc_ggeom calls dqmc_hub_input_hsf, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_verify calls dqmc_hub_init
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl