DQMC_2DPerl_DC_Imp2 – Quest
DQMC_2DPerl_DC_Imp2 Subroutine
47 statements
Source File
public subroutine DQMC_2DPerl_DC_Imp2(n, nx, ny, S, cord)
using lookup table (maybe hashing table) compute the index of i initial the index of j compute the index of j compute the distance
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: nx
integer, intent(in) :: ny
type(Struct), intent(inout) :: S
real(kind=wp), pointer :: cord(:,:)
Called by
Call graph
dqmc_init_2dperl calls dqmc_2dperl_dc_imp2
dqmc_comp_2dperl calls dqmc_init_2dperl
dqmc_verify calls dqmc_init_2dperl
dqmc_test calls dqmc_comp_2dperl