DQMC_ComputeG – Quest
DQMC_ComputeG Subroutine
128 statements
Source File
public subroutine DQMC_ComputeG(il, n, sgn, G, V, SB, pvt2, compDet, det, sxx)
Setup index for B_{i} Compute the LU decomposition of T first. Solve T'W = U. W = transpose(inv(U)inv(T))
Compute WD1+D2 = transpose(inv(U)inv(T))D1+D2 = transpose(D1*inv(U)inv(T) + D2)
Compute the LU decomposition of W1. G = inv(U), which is transpose of U. G = D1G = D1inv(U) Solve W'G = inv(U), G = inv(W')G Solve TG = inv(W')inv(U), G = inv(T)inv(W')D1inv(U) Compute the LU decomposition of U first.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: il
integer, intent(in) :: n
real(kind=wp), intent(inout) :: sgn
real(kind=wp), intent(inout) :: G(:,:)
real(kind=wp), intent(in) :: V(:,:)
type(SeqB), intent(inout) :: SB
integer, intent(inout) :: pvt2(:)
logical, intent(in) :: compDet
real(kind=wp), intent(inout) :: det
logical, intent(in) :: sxx
Calls
Called by
Call graph
dqmc_computeg calls blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_error, dqmc_scalerow, dqmc_seqmultb, dqmc_trans, dqmc_warning
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_eye, dqmc_getb, dqmc_multb_left, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_multb_left calls dqmc_error, dqmc_scalerow, blas_dgemm, blas_dscal, dexp, lapack_dsyev
dqmc_udtd calls blas_dcopy, dqmc_error, blas_dscal, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_scalecol
dqmc_multb_right calls dqmc_error, blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_getg calls dqmc_computeg
dqmc_hol_sweep3_cont calls dqmc_computeg
dqmc_hub_sweep2_cont calls dqmc_computeg
dqmc_hub_init calls dqmc_getg
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_ggeom calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_verify calls dqmc_hub_init, dqmc_hub_run
dqmc_test calls dqmc_comp_2dperl