DQMC_MultBi_Left – Quest
DQMC_MultBi_Left Subroutine
39 statements
Source File
public subroutine DQMC_MultBi_Left(n, M, B, V_i, C)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout), target :: M(n,n)
type(matB), intent(inout) :: B
real(kind=wp), intent(in) :: V_i(n)
real(kind=wp), intent(inout), target :: C(n,n)
Calls
Called by
Call graph
dqmc_multbi_left calls daxpy, dscal, dqmc_scalecol, dqmc_trans
dqmc_scalecol calls dscal
dqmc_getbi calls dqmc_multbi_left