DQMC_TDM1_SelfEnergy – Quest
DQMC_TDM1_SelfEnergy Subroutine
135 statements
Source File
public subroutine DQMC_TDM1_SelfEnergy(T1, tau, OPT)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(TDM1), intent(in) :: T1
type(Gtau), intent(inout) :: tau
integer, intent(in) :: OPT
Calls
Called by
Call graph
dqmc_tdm1_selfenergy calls dqmc_print_array, dqmc_getftk, dqmc_gtau_getg0, zgemv, zgetrf, zgetri
dqmc_print_array calls dqmc_print_complexarray, dqmc_print_realarray
dqmc_getftk calls dconjg
dqmc_gtau_getg0 calls dcopy, dgemm, dsyev, dqmc_getb, dqmc_scalecol
dqmc_getb calls dqmc_multb_right, dqmc_scalerow
dqmc_scalecol calls dscal
dqmc_multb_right calls dqmc_scalecol, blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error
dqmc_scalerow calls dscal
dqmc_ggeom calls dqmc_tdm1_selfenergy