DQMC_SeqMultBi – Quest
DQMC_SeqMultBi Subroutine
46 statements
Source File
public subroutine DQMC_SeqMultBi(il, ir, SB, V)
R = I, R will be the R-factor of the QDR factorization The UDT decomposition is performed at every nOrth step, and at the last step. In other steps, we just multiply B_i to the Q-factor multiply B_i to the Q-factor
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: il
integer, intent(in) :: ir
type(SeqB), intent(inout) :: SB
real(kind=wp), intent(in) :: V(SB%n,SB%L)
Calls
Called by
Call graph
dqmc_seqmultbi calls dqmc_eye, dqmc_getbi, dqmc_multbi_left, dqmc_udtd
dqmc_getbi calls dqmc_multbi_right, dqmc_scalecolinv
dqmc_multbi_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerowinv
dqmc_udtd calls blas_dcopy, blas_dscal, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_error, dqmc_scalecol
dqmc_multbi_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecolinv
dqmc_scalecol calls dscal
dqmc_scalecolinv calls dscal
dqmc_scalerowinv calls dscal
dqmc_getgtau calls dqmc_seqmultbi
dqmc_makegtau calls dqmc_getgtau