DQMC_Hub_Init_Vmat – Quest
DQMC_Hub_Init_Vmat Subroutine
60 statements
Source File
public subroutine DQMC_Hub_Init_Vmat(Hub)
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout) :: Hub
Called by
Call graph
dqmc_hub_init calls dqmc_hub_init_vmat
dqmc_ggeom calls dqmc_hub_init_vmat, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_verify calls dqmc_hub_init
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl