DQMC_Gtau_Init – Quest
DQMC_Gtau_Init Subroutine
61 statements
Source File
public subroutine DQMC_Gtau_Init(Hub, tau)
Uses
DQMC_Hubbard
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(in), target :: Hub
type(Gtau), intent(inout) :: tau
Calls
Called by
Call graph
dqmc_gtau_init calls lapack_dgetri, dqmc_error
dqmc_ggeom calls dqmc_gtau_init