DQMC_Hub_Sweep2 – Quest
DQMC_Hub_Sweep2 Subroutine
115 statements
Source File
public subroutine DQMC_Hub_Sweep2(Hub, numTry)
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout) :: Hub
integer, intent(in) :: numTry
Calls
Called by
Call graph
dqmc_hub_sweep2 calls dqmc_getg, dqmc_gfun_copyup, ran0
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
ran0 calls dlarnv
dqmc_computeg calls blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_error, dqmc_scalerow, dqmc_seqmultb, dqmc_trans, dqmc_warning
dqmc_multb_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerow
dqmc_multbi_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecolinv
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_multb_left, dqmc_eye, dqmc_getb, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_udtd calls blas_dcopy, blas_dscal, dqmc_error, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_scalecol
dqmc_multb_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_hub_run calls dqmc_hub_sweep2