DQMC_Config_isSet – Quest
DQMC_Config_isSet Function
13 statements
Source File
public function DQMC_Config_isSet(cfg, name) result(isSet)
Arguments
Type Intent Optional Attributes Name
type(config), intent(in) :: cfg
character(len=*), intent(in) :: name
Return Value logical
Calls
Called by
Call graph
dqmc_config_isset calls dqmc_error, dqmc_find_param
dqmc_hub_config calls dqmc_config_isset
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl