DQMC_Phy2_Meas – Quest
DQMC_Phy2_Meas Subroutine
20 statements
Source File
public subroutine DQMC_Phy2_Meas(n, M1, M2, P2, Bond, G_up, G_dn, sgn)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout) :: M1(:,:)
real(kind=wp), intent(inout) :: M2(:,:)
type(Phy2), intent(inout) :: P2
type(CCS), intent(in) :: Bond
real(kind=wp), intent(in) :: G_up(n,n)
real(kind=wp), intent(in) :: G_dn(n,n)
real(kind=wp), intent(in) :: sgn
Calls
Called by
Call graph
dqmc_phy2_meas calls blas_daxpy, dqmc_phy2_pair
dqmc_hub_fullmeas calls dqmc_phy2_meas
dqmc_hub_meas calls dqmc_phy2_meas
dqmc_hub_sweep calls dqmc_phy2_meas
dqmc_hub_sweep_cont calls dqmc_phy2_meas
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep
dqmc_hub_run calls dqmc_hub_sweep
dqmc_ggeom calls dqmc_hub_fullmeas, dqmc_hub_meas, dqmc_hub_sweep
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run