DQMC_Hub_Run – Quest
DQMC_Hub_Run Subroutine
30 statements
Source File
public subroutine DQMC_Hub_Run(Hub, Info)
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout) :: Hub
integer :: Info
Calls
Called by
Call graph
dqmc_hub_run calls dqmc_phy2_avg, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_phy0_avg, dqmc_phy0_geterr, dqmc_phy2_geterr
dqmc_phy2_avg calls dqmc_phy2_avg_symm, dqmc_phy2_avg_wave
dqmc_hub_sweep calls dqmc_applyupdate, dqmc_getg, dqmc_getg_2nd_order, dqmc_gfun_copyup, dqmc_gfun_getjj, dqmc_phy0_meas, dqmc_phy2_meas, dqmc_syncwraps, dqmc_updateg, dqmc_updatewraps, ran0
dqmc_hub_sweep2 calls dqmc_getg, dqmc_gfun_copyup, ran0
dqmc_phy0_avg calls blas_dscal, dqmc_error
dqmc_phy0_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_phy2_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_jackknife calls dqmc_jackknife_complex, dqmc_jackknife_real
dqmc_signjackknife calls dqmc_signjackknife_complex, dqmc_signjackknife_real
dqmc_applyupdate calls blas_dgemm
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
dqmc_gfun_getjj calls blas_ddot
dqmc_phy0_meas calls blas_daxpy, blas_dgemm
dqmc_phy2_avg_symm calls dqmc_pair_symm
dqmc_phy2_avg_wave calls dqmc_wave_avg
dqmc_phy2_meas calls blas_daxpy, dqmc_phy2_pair
dqmc_updateg calls blas_dscal, dqmc_applyupdate, blas_dgemv
ran0 calls dlarnv
dqmc_computeg calls dqmc_error, blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_scalerow, dqmc_seqmultb, dqmc_trans, dqmc_warning
dqmc_multb_left calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalerow
dqmc_multbi_right calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalecolinv
dqmc_wave_avg calls blas_ddot, blas_dgemm
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_multb_left, dqmc_eye, dqmc_getb, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_udtd calls blas_dscal, dqmc_error, blas_dcopy, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_scalecol
dqmc_multb_right calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_verify calls dqmc_hub_run