DQMC_Gtau_SetAlias – Quest
DQMC_Gtau_SetAlias Subroutine
41 statements
Source File
public subroutine DQMC_Gtau_SetAlias(spin, tau, A, B, V, gt0, g0t, g00, gtt, it, i0, itau, sgn)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: spin
type(Gtau), intent(in), target :: tau
real(kind=wp), optional, pointer :: A(:,:)
type(matB), optional, pointer :: B
real(kind=wp), optional, pointer :: V(:,:)
real(kind=wp), optional, pointer :: gt0(:,:)
real(kind=wp), optional, pointer :: g0t(:,:)
real(kind=wp), optional, pointer :: g00(:,:)
real(kind=wp), optional, pointer :: gtt(:,:)
integer, optional, pointer :: it
integer, optional, pointer :: i0
integer, optional, pointer :: itau(:)
real(kind=wp), optional, pointer :: sgn
Called by
Call graph
dqmc_change_gtau_time calls dqmc_gtau_setalias
dqmc_gtau_dumpa calls dqmc_gtau_setalias
dqmc_gtau_loada calls dqmc_gtau_setalias
dqmc_makegtau calls dqmc_change_gtau_time
dqmc_tdm1_meas calls dqmc_change_gtau_time, dqmc_gtau_dumpa
dqmc_tdm1_meas_para calls dqmc_change_gtau_time, dqmc_gtau_dumpa
dqmc_ggeom calls dqmc_gtau_loada, dqmc_tdm1_meas, dqmc_tdm1_meas_para