DQMC_Geom_Fill – Quest
DQMC_Geom_Fill Subroutine
52 statements
Source File
public subroutine DQMC_Geom_Fill(gwrap, gfile, cfg, SOP)
Arguments
Type Intent Optional Attributes Name
type(GeomWrap), intent(inout) :: gwrap
character(len=60), intent(in) :: gfile
type(config), intent(inout) :: cfg
integer, intent(in) :: SOP
Calls
Called by
Call graph
dqmc_geom_fill calls analyze_input, assign_gf_phase, assign_phase, construct_bond_classes, construct_hamilt, construct_lattice, construct_lattice_classes, construct_pair_classes, construct_pairs, construct_recip_lattice, construct_recip_lattice_classes, count_hop_class, count_local_classes, dqmc_error, dqmc_fill_fourierc, init_lattice, init_recip_latt, map_symm_bonds, map_symm_lattice, map_symm_pairs, map_symm_recip_lattice, read_bonds, read_symm
assign_phase calls convert_to_fractional, get_det, get_inverse, move_to_record
construct_hamilt calls cfg_get, dqmc_hamilt_groupckb, find_neighbors, hoptowho, move_to_record
construct_lattice calls get_inverse
construct_pairs calls hoptowho, move_to_record
construct_recip_lattice calls closer_to_zero, get_inverse
init_lattice calls convert_to_fractional, count_atom, get_det, get_inverse, move_to_record
init_recip_latt calls cfg_get, get_inverse
map_symm_bonds calls get_inverse, hoptowho
map_symm_lattice calls apply_point_symm, get_inverse
map_symm_recip_lattice calls apply_point_symm, get_inverse
read_bonds calls move_to_record
read_symm calls count_symmetry, move_to_record
cfg_get calls dqmc_config_geti, dqmc_config_getpi, dqmc_config_getpr, dqmc_config_getr, dqmc_config_gets
count_atom calls move_to_record
count_symmetry calls move_to_record
hoptowho calls get_inverse
dqmc_config_geti calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpi calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_gets calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_ggeom calls dqmc_geom_fill