DQMC_MultB_Right – Quest
DQMC_MultB_Right Subroutine
34 statements
Source File
public subroutine DQMC_MultB_Right(n, M, B, V_i, C)
Check error message
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout) :: M(n,n)
type(matB), intent(in) :: B
real(kind=wp), intent(in) :: V_i(n)
real(kind=wp), intent(inout) :: C(n,n)
Calls
Called by
Call graph
dqmc_multb_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_change_gtau_time calls dqmc_multb_right
dqmc_getb calls dqmc_multb_right
dqmc_gtau_loada calls dqmc_multb_right, dqmc_getb
dqmc_gtau_getg0 calls dqmc_getb
dqmc_makegtau calls dqmc_change_gtau_time, dqmc_getgtau
dqmc_seqmultb calls dqmc_getb
dqmc_tdm1_meas calls dqmc_change_gtau_time
dqmc_tdm1_meas_para calls dqmc_change_gtau_time
dqmc_ggeom calls dqmc_gtau_loada, dqmc_tdm1_meas, dqmc_tdm1_meas_para, dqmc_tdm1_selfenergy, dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_computeg calls dqmc_seqmultb
dqmc_getgtau calls dqmc_seqmultb
dqmc_tdm1_selfenergy calls dqmc_gtau_getg0
dqmc_getg calls dqmc_computeg
dqmc_hol_sweep3_cont calls dqmc_computeg
dqmc_hub_sweep2_cont calls dqmc_computeg
dqmc_hub_init calls dqmc_getg
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_verify calls dqmc_hub_init, dqmc_hub_run
dqmc_test calls dqmc_comp_2dperl