DQMC_Phy2_GetErrIrrep – Quest
DQMC_Phy2_GetErrIrrep Subroutine
51 statements
Source File
public subroutine DQMC_Phy2_GetErrIrrep(P2, G_fun, S)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(Phy2), intent(inout) :: P2
real(kind=wp), intent(in) :: G_fun(S%nClass,P2%err)
type(Struct), intent(in) :: S
Calls
Called by
Call graph
dqmc_phy2_geterrirrep calls dqmc_phy2_pair, dqmc_wave_avg
dqmc_wave_avg calls blas_ddot, blas_dgemm
dqmc_ggeom calls dqmc_phy2_geterrirrep