DQMC_ScaleCol – Quest
DQMC_ScaleCol Subroutine
9 statements
Source File
public subroutine DQMC_ScaleCol(n, A, D)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=WP), intent(inout) :: A(n,n)
real(kind=WP), intent(in) :: D(n)
Calls
Called by
Call graph
dqmc_scalecol calls dscal
dqmc_getgtau calls dqmc_scalecol, dqmc_seqmultb, dqmc_seqmultbi
dqmc_gtau_getg0 calls dqmc_scalecol, dqmc_getb
dqmc_multb_left calls dqmc_scalecol
dqmc_multb_right calls dqmc_scalecol
dqmc_multbi_left calls dqmc_scalecol
dqmc_multbi_right calls dqmc_scalecol
dqmc_udtd calls dqmc_scalecol
dqmc_change_gtau_time calls dqmc_multb_right
dqmc_getb calls dqmc_multb_right, dqmc_multb_left
dqmc_getbi calls dqmc_multbi_left
dqmc_gtau_loada calls dqmc_multb_right, dqmc_getb
dqmc_makegtau calls dqmc_getgtau, dqmc_change_gtau_time
dqmc_seqmultb calls dqmc_udtd, dqmc_getb
dqmc_seqmultbi calls dqmc_udtd
dqmc_tdm1_selfenergy calls dqmc_gtau_getg0
dqmc_computeg calls dqmc_seqmultb
dqmc_tdm1_meas calls dqmc_change_gtau_time
dqmc_tdm1_meas_para calls dqmc_change_gtau_time
dqmc_ggeom calls dqmc_gtau_loada, dqmc_tdm1_selfenergy, dqmc_tdm1_meas, dqmc_tdm1_meas_para, dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_getg calls dqmc_computeg
dqmc_hol_sweep3_cont calls dqmc_computeg
dqmc_hub_sweep2_cont calls dqmc_computeg
dqmc_hub_init calls dqmc_getg
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_verify calls dqmc_hub_init, dqmc_hub_run
dqmc_test calls dqmc_comp_2dperl