DQMC_Hol_Sweep3_Cont – Quest
DQMC_Hol_Sweep3_Cont Subroutine
138 statements
Source File
public subroutine DQMC_Hol_Sweep3_Cont(Hub, numTry)
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout) :: Hub
integer, intent(in) :: numTry
Calls
Call graph
dqmc_hol_sweep3_cont calls dqmc_computeg, ran0
dqmc_computeg calls blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_error, dqmc_scalerow, dqmc_seqmultb, dqmc_trans, dqmc_warning
ran0 calls dlarnv
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_eye, dqmc_getb, dqmc_multb_left, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_multb_left calls dqmc_error, dqmc_scalerow, blas_dgemm, blas_dscal, dexp, lapack_dsyev
dqmc_udtd calls blas_dcopy, dqmc_error, blas_dscal, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_scalecol
dqmc_multb_right calls dqmc_error, blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_scalecol
dqmc_scalecol calls dscal