DQMC_Phy0_Print – Quest
DQMC_Phy0_Print Subroutine
22 statements
Source File
public subroutine DQMC_Phy0_Print(P0, S, OPT)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(Phy0), intent(in) :: P0
type(Struct), intent(in) :: S
integer, intent(in) :: OPT
Calls
Called by
Call graph
dqmc_phy0_print calls dqmc_print_realarray
dqmc_hub_print calls dqmc_phy0_print
dqmc_ggeom calls dqmc_phy0_print
dqmc_comp_2dperl calls dqmc_hub_print
dqmc_test calls dqmc_comp_2dperl