DQMC_Wave_Avg – Quest
DQMC_Wave_Avg Subroutine
16 statements
Source File
public subroutine DQMC_Wave_Avg(nB, nWave, W, T, I, O, factor, ldt)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nB
integer, intent(in) :: nWave
real(kind=wp), intent(in) :: W(nb,nWave)
real(kind=wp), intent(in) :: T(ldt,nWave)
real(kind=wp), intent(in) :: I(nb,nb)
real(kind=wp), intent(inout) :: O(:)
real(kind=wp), intent(in) :: factor
integer, intent(in) :: ldt
Calls
Called by
Call graph
dqmc_wave_avg calls blas_ddot, blas_dgemm
dqmc_phy2_avg_wave calls dqmc_wave_avg
dqmc_phy2_geterrirrep calls dqmc_wave_avg
dqmc_tdm2_avg calls dqmc_wave_avg
dqmc_phy2_avg calls dqmc_phy2_avg_wave
dqmc_ggeom calls dqmc_phy2_geterrirrep, dqmc_phy2_avg
dqmc_comp_2dperl calls dqmc_phy2_avg
dqmc_hub_run calls dqmc_phy2_avg
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run