DQMC_MakeGtau – Quest
DQMC_MakeGtau Subroutine
32 statements
Source File
public subroutine DQMC_MakeGtau(tau, it, i0)
Arguments
Type Intent Optional Attributes Name
type(Gtau), intent(inout) :: tau
integer, intent(in) :: it
integer, intent(in) :: i0
Calls
Call graph
dqmc_makegtau calls dqmc_change_gtau_time, dqmc_getgtau
dqmc_change_gtau_time calls dqmc_gtau_setalias, dqmc_multb_left, dqmc_multb_right, dqmc_multbi_left, dqmc_multbi_right
dqmc_getgtau calls blas_daxpy, blas_dcopy, blas_dgemm, lapack_dgesv, lapack_dgetrf, lapack_dgetri, lapack_dgetrs, dqmc_error, dqmc_eye, dqmc_scalecol, dqmc_scalerow, dqmc_seqmultb, dqmc_seqmultbi, dqmc_trans
dqmc_multb_left calls blas_dgemm, dqmc_error, dqmc_scalerow, blas_dscal, dexp, lapack_dsyev
dqmc_multb_right calls blas_dgemm, dqmc_error, dqmc_scalecol, blas_dscal, dexp, lapack_dsyev
dqmc_multbi_left calls blas_dgemm, dqmc_error, blas_dscal, dexp, lapack_dsyev, dqmc_scalerowinv
dqmc_multbi_right calls blas_dgemm, dqmc_error, blas_dscal, dexp, lapack_dsyev, dqmc_scalecolinv
dqmc_scalecol calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_eye, dqmc_multb_left, dqmc_getb, dqmc_udtd
dqmc_seqmultbi calls dqmc_eye, dqmc_multbi_left, dqmc_getbi, dqmc_udtd
dqmc_getb calls dqmc_multb_right, dqmc_scalerow
dqmc_getbi calls dqmc_multbi_right, dqmc_scalecolinv
dqmc_scalecolinv calls dscal
dqmc_scalerowinv calls dscal
dqmc_udtd calls blas_dcopy, dqmc_error, dqmc_scalecol, blas_dscal, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr