DQMC_UDTD – Quest
DQMC_UDTD Subroutine
36 statements
Source File
public subroutine DQMC_UDTD(n, U, D, T, W1, W2, rw, tau, piv, lwork)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout) :: U(n,n)
real(kind=wp), intent(inout) :: D(n)
real(kind=wp), intent(inout) :: T(n,n)
real(kind=wp), intent(inout) :: W1(n,n)
real(kind=wp), intent(inout) :: W2(n,n)
real(kind=wp), intent(inout) :: rw(:)
real(kind=wp), intent(inout) :: tau(n)
integer, intent(inout) :: piv(:)
integer, intent(in) :: lwork(:)
Calls
Called by
Call graph
dqmc_udtd calls blas_dcopy, blas_dscal, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_error, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_seqmultb calls dqmc_udtd
dqmc_seqmultbi calls dqmc_udtd
dqmc_computeg calls dqmc_seqmultb
dqmc_getgtau calls dqmc_seqmultb, dqmc_seqmultbi
dqmc_getg calls dqmc_computeg
dqmc_hol_sweep3_cont calls dqmc_computeg
dqmc_hub_sweep2_cont calls dqmc_computeg
dqmc_makegtau calls dqmc_getgtau
dqmc_hub_init calls dqmc_getg
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_ggeom calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_verify calls dqmc_hub_init, dqmc_hub_run
dqmc_test calls dqmc_comp_2dperl