DQMC_ScaleColInv – Quest
DQMC_ScaleColInv Subroutine
11 statements
Source File
public subroutine DQMC_ScaleColInv(n, A, D)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=WP), intent(inout) :: A(n,n)
real(kind=WP), intent(in) :: D(n)
Calls
Called by
Call graph
dqmc_scalecolinv calls dscal
dqmc_getbi calls dqmc_scalecolinv, dqmc_multbi_right
dqmc_multbi_right calls dqmc_scalecolinv
dqmc_change_gtau_time calls dqmc_multbi_right
dqmc_getg calls dqmc_multbi_right
dqmc_seqmultbi calls dqmc_getbi
dqmc_getgtau calls dqmc_seqmultbi
dqmc_hub_init calls dqmc_getg
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_makegtau calls dqmc_change_gtau_time, dqmc_getgtau
dqmc_tdm1_meas calls dqmc_change_gtau_time
dqmc_tdm1_meas_para calls dqmc_change_gtau_time
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_ggeom calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_tdm1_meas, dqmc_tdm1_meas_para, dqmc_hub_config
dqmc_verify calls dqmc_hub_init, dqmc_hub_run
dqmc_test calls dqmc_comp_2dperl