DQMC_SyncWraps – Quest
DQMC_SyncWraps Subroutine
16 statements
Source File
public subroutine DQMC_SyncWraps(G1, G2)
Arguments
Type Intent Optional Attributes Name
type(G_fun), intent(inout) :: G1
type(G_fun), intent(inout) :: G2
Called by
Call graph
dqmc_hub_sweep calls dqmc_syncwraps
dqmc_comp_2dperl calls dqmc_hub_sweep
dqmc_hub_run calls dqmc_hub_sweep
dqmc_ggeom calls dqmc_hub_sweep
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run