DQMC_GetBi – Quest
DQMC_GetBi Subroutine
9 statements
Source File
public subroutine DQMC_GetBi(n, M, B, V_i, C)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(inout) :: M(n,n)
type(matB), intent(inout) :: B
real(kind=wp), intent(in) :: V_i(n)
real(kind=wp), intent(inout) :: C(n,n)
Calls
Call graph
dqmc_getbi calls dqmc_eye, dqmc_multbi_left
dqmc_multbi_left calls daxpy, dscal, dqmc_scalecol, dqmc_trans
dqmc_scalecol calls dscal