DQMC_Hub_Print – Quest
DQMC_Hub_Print Subroutine
9 statements
Source File
public subroutine DQMC_Hub_Print(Hub, OPT)
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(in) :: Hub
integer, intent(in) :: OPT
Calls
Called by
Call graph
dqmc_hub_print calls dqmc_hub_outputparam, dqmc_phy0_print, dqmc_phy2_print
dqmc_hub_outputparam calls dqmc_hub_output_hsf, dqmc_warning
dqmc_phy0_print calls dqmc_print_realarray
dqmc_phy2_print calls dqmc_print_realarray
dqmc_comp_2dperl calls dqmc_hub_print
dqmc_test calls dqmc_comp_2dperl