DQMC_Config_SetR – Quest
DQMC_Config_SetR Subroutine
13 statements
Source File
public subroutine DQMC_Config_SetR(cfg, name, value)
Arguments
Type Intent Optional Attributes Name
type(config), intent(inout) :: cfg
character(len=*), intent(in) :: name
real(kind=wp), intent(in) :: value
Calls
Called by
Call graph
dqmc_config_setr calls dqmc_error, dqmc_find_param
cfg_set calls dqmc_config_setr
dqmc_geom_init calls cfg_set
dqmc_hub_config calls cfg_set
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_geom_init, dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl