DQMC_GFun_CopyUp – Quest
DQMC_GFun_CopyUp Subroutine
20 statements
Source File
public subroutine DQMC_GFun_CopyUp(G1, G2, P)
Arguments
Type Intent Optional Attributes Name
type(G_fun), intent(inout) :: G1
type(G_fun), intent(in) :: G2
real(kind=wp), intent(in) :: P(G2%n)
Called by
Call graph
dqmc_hub_fullmeas calls dqmc_gfun_copyup
dqmc_hub_meas calls dqmc_gfun_copyup
dqmc_hub_sweep calls dqmc_gfun_copyup
dqmc_hub_sweep2 calls dqmc_gfun_copyup
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_ggeom calls dqmc_hub_fullmeas, dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run