DQMC_Gfun_Getjj – Quest
DQMC_Gfun_Getjj Function
12 statements
Source File
public function DQMC_Gfun_Getjj(n, j, blksz, G, U, W) result(gjj)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: j
integer, intent(in) :: blksz
real(kind=wp), intent(in) :: G(n,n)
real(kind=wp), intent(in) :: U(n,n)
real(kind=wp), intent(in) :: W(n,n)
Return Value real(kind=wp)
Calls
Called by
Call graph
dqmc_gfun_getjj calls blas_ddot
dqmc_hub_sweep calls dqmc_gfun_getjj
dqmc_hub_sweep_cont calls dqmc_gfun_getjj
dqmc_comp_2dperl calls dqmc_hub_sweep
dqmc_hub_run calls dqmc_hub_sweep
dqmc_ggeom calls dqmc_hub_sweep
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run