DQMC_Hub_Sweep – Quest
DQMC_Hub_Sweep Subroutine
156 statements
Source File
public subroutine DQMC_Hub_Sweep(Hub, nMeas0)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout), target :: Hub
integer, intent(in) :: nMeas0
Calls
Called by
Call graph
dqmc_hub_sweep calls dqmc_applyupdate, dqmc_getg, dqmc_getg_2nd_order, dqmc_gfun_copyup, dqmc_gfun_getjj, dqmc_phy0_meas, dqmc_phy2_meas, dqmc_syncwraps, dqmc_updateg, dqmc_updatewraps, ran0
dqmc_applyupdate calls blas_dgemm
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
dqmc_gfun_getjj calls blas_ddot
dqmc_phy0_meas calls blas_daxpy, blas_dgemm
dqmc_phy2_meas calls blas_daxpy, dqmc_phy2_pair
dqmc_updateg calls dqmc_applyupdate, blas_dgemv, blas_dscal
ran0 calls dlarnv
dqmc_computeg calls blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_error, dqmc_scalerow, dqmc_seqmultb, dqmc_trans, dqmc_warning
dqmc_multb_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerow
dqmc_multbi_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecolinv
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_multb_left, dqmc_eye, dqmc_getb, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_udtd calls blas_dcopy, blas_dscal, dqmc_error, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_scalecol
dqmc_multb_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_comp_2dperl calls dqmc_hub_sweep
dqmc_hub_run calls dqmc_hub_sweep
dqmc_ggeom calls dqmc_hub_sweep
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run