DQMC_SeqB_Init – Quest
DQMC_SeqB_Init Subroutine
22 statements
Source File
public subroutine DQMC_SeqB_Init(n, L, nOrth, B, SB, WS)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: L
integer, intent(in) :: nOrth
type(matB), intent(in), target :: B
type(SeqB), intent(inout) :: SB
type(WSpace), intent(in), target :: WS
Called by
Call graph
dqmc_hub_init calls dqmc_seqb_init
dqmc_hub_config calls dqmc_hub_init
dqmc_verify calls dqmc_hub_init
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl