DQMC_JackKnife_Complex – Quest
DQMC_JackKnife_Complex Subroutine
31 statements
Source File
public subroutine DQMC_JackKnife_Complex(n, avg, err, x, y, sgn, sum_sgn)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
complex(kind=wp), intent(out) :: avg
complex(kind=wp), intent(out) :: err
complex(kind=wp), intent(in) :: x(n)
complex(kind=wp), intent(out) :: y(n)
complex(kind=wp), intent(out) :: sgn(n)
complex(kind=wp), intent(out) :: sum_sgn
Called by
Call graph
dqmc_jackknife calls dqmc_jackknife_complex
dqmc_phy0_geterr calls dqmc_jackknife
dqmc_phy2_geterr calls dqmc_jackknife
dqmc_tdm1_geterr calls dqmc_jackknife
dqmc_comp_2dperl calls dqmc_phy0_geterr, dqmc_phy2_geterr
dqmc_hub_run calls dqmc_phy0_geterr, dqmc_phy2_geterr
dqmc_ggeom calls dqmc_phy0_geterr, dqmc_phy2_geterr, dqmc_tdm1_geterr
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run