DQMC_Phy0_GetErr – Quest
DQMC_Phy0_GetErr Subroutine
72 statements
Source File
public subroutine DQMC_Phy0_GetErr(P0)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(Phy0), intent(inout) :: P0
Calls
Called by
Call graph
dqmc_phy0_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_jackknife calls dqmc_jackknife_complex, dqmc_jackknife_real
dqmc_signjackknife calls dqmc_signjackknife_complex, dqmc_signjackknife_real
dqmc_comp_2dperl calls dqmc_phy0_geterr
dqmc_hub_run calls dqmc_phy0_geterr
dqmc_ggeom calls dqmc_phy0_geterr
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run