DQMC_Hub_Config – Quest
DQMC_Hub_Config Subroutine
72 statements
Source File
public subroutine DQMC_Hub_Config(Hub, cfg)
Uses
DQMC_MPI
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout) :: Hub
type(config), intent(inout) :: cfg
Calls
Called by
Call graph
dqmc_hub_config calls cfg_get, cfg_set, dqmc_config_isset, dqmc_hub_init, dqmc_warning
cfg_get calls dqmc_config_geti, dqmc_config_getpi, dqmc_config_getpr, dqmc_config_getr, dqmc_config_gets
cfg_set calls dqmc_config_seti, dqmc_config_setpi, dqmc_config_setpr, dqmc_config_setr, dqmc_config_sets
dqmc_config_isset calls dqmc_error, dqmc_find_param
dqmc_hub_init calls dqmc_warning, dqmc_b_init, dqmc_error, dqmc_getg, dqmc_gfun_clone, dqmc_gfun_init, dqmc_hub_init_vmat, dqmc_hub_input_hsf, dqmc_phy0_init, dqmc_phy2_init, dqmc_seqb_init, dqmc_wspace_allocate, ran0, ran1
dqmc_b_init calls dqmc_b_expinit
dqmc_config_geti calls dqmc_warning, dqmc_error, dqmc_find_param
dqmc_config_getpi calls dqmc_warning, dqmc_error, dqmc_find_param
dqmc_config_getpr calls dqmc_warning, dqmc_error, dqmc_find_param
dqmc_config_getr calls dqmc_warning, dqmc_error, dqmc_find_param
dqmc_config_gets calls dqmc_warning, dqmc_error, dqmc_find_param
dqmc_config_seti calls dqmc_error, dqmc_find_param
dqmc_config_setpi calls dqmc_error, dqmc_find_param
dqmc_config_setpr calls dqmc_error, dqmc_find_param
dqmc_config_setr calls dqmc_error, dqmc_find_param
dqmc_config_sets calls dqmc_error, dqmc_find_param
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
dqmc_hub_input_hsf calls dqmc_error
dqmc_wspace_allocate calls lapack_dgeqp3, lapack_dgetri, lapack_dorgqr, lapack_dormqr, lapack_dsyev
ran0 calls dlarnv
ran1 calls dlarnv
dqmc_b_expinit calls dqmc_error, lapack_dsyev, blas_dgemm, blas_dscal, dexp
dqmc_computeg calls dqmc_warning, dqmc_error, blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_scalerow, dqmc_seqmultb, dqmc_trans
dqmc_multb_left calls dqmc_error, lapack_dsyev, blas_dgemm, blas_dscal, dexp, dqmc_scalerow
dqmc_multbi_right calls dqmc_error, lapack_dsyev, blas_dgemm, blas_dscal, dexp, dqmc_scalecolinv
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_multb_left, dqmc_eye, dqmc_getb, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_udtd calls dqmc_error, blas_dcopy, lapack_dgeqp3, lapack_dorgqr, blas_dscal, blas_dtrmm, dqmc_scalecol
dqmc_multb_right calls dqmc_error, lapack_dsyev, blas_dgemm, blas_dscal, dexp, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl