DQMC_Print_RealArray – Quest
DQMC_Print_RealArray Subroutine
20 statements
Source File
public subroutine DQMC_Print_RealArray(n, m, title, label, avg, err, OPT)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: m
character(len=*), intent(in) :: title
character(len=*), intent(in) :: label(:)
real(kind=wp), intent(in) :: avg(:,:)
real(kind=wp), intent(in) :: err(:,:)
integer, intent(in) :: OPT
Called by
Call graph
dqmc_print_array calls dqmc_print_realarray
dqmc_phy0_print calls dqmc_print_realarray
dqmc_phy0_printft calls dqmc_print_realarray
dqmc_phy2_print calls dqmc_print_realarray
dqmc_hub_print calls dqmc_phy0_print, dqmc_phy2_print
dqmc_tdm1_print calls dqmc_print_array
dqmc_tdm1_printkft calls dqmc_print_array
dqmc_tdm1_selfenergy calls dqmc_print_array
dqmc_ggeom calls dqmc_phy0_print, dqmc_phy0_printft, dqmc_phy2_print, dqmc_tdm1_print, dqmc_tdm1_printkft, dqmc_tdm1_selfenergy
dqmc_comp_2dperl calls dqmc_hub_print
dqmc_test calls dqmc_comp_2dperl