DQMC_GFun_Duplicate – Quest
DQMC_GFun_Duplicate Subroutine
30 statements
Source File
public subroutine DQMC_GFun_Duplicate(G1, G2)
Arguments
Type Intent Optional Attributes Name
type(G_fun), intent(inout) :: G1
type(G_fun), intent(in) :: G2
Called by
Call graph
dqmc_hub_fullmeas calls dqmc_gfun_duplicate
dqmc_hub_meas calls dqmc_gfun_duplicate
dqmc_comp_2dperl calls dqmc_hub_meas
dqmc_ggeom calls dqmc_hub_fullmeas, dqmc_hub_meas
dqmc_test calls dqmc_comp_2dperl