DQMC_TDM1_Init – Quest
DQMC_TDM1_Init Subroutine
25 statements
Source File
public subroutine DQMC_TDM1_Init(L, dtau, T1, nBin, S, Gwrap)
Uses
DQMC_GEOM_WRAP
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: L
real(kind=wp), intent(in) :: dtau
type(TDM1), intent(inout) :: T1
integer, intent(in) :: nBin
type(Struct), intent(in) :: S
type(GeomWrap), intent(in) :: Gwrap
Calls
Called by
Call graph
dqmc_tdm1_init calls dqmc_tdm1_initftw, dqmc_tdm1_initprop
dqmc_ggeom calls dqmc_tdm1_init