DQMC_GetGtau – Quest
DQMC_GetGtau Subroutine
150 statements
Source File
public subroutine DQMC_GetGtau(it, i0, spin, gt0, g0t, g00, gtt, tau)
*** We need to keep T2 and U1 for later use.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it
integer, intent(in) :: i0
integer, intent(in) :: spin
real(kind=wp), intent(inout) :: gt0(:,:)
real(kind=wp), intent(inout) :: g0t(:,:)
real(kind=wp), intent(inout) :: g00(:,:)
real(kind=wp), intent(inout) :: gtt(:,:)
type(Gtau), intent(inout), target :: tau
Calls
Called by
Call graph
dqmc_getgtau calls blas_daxpy, blas_dcopy, blas_dgemm, lapack_dgesv, lapack_dgetrf, lapack_dgetri, lapack_dgetrs, dqmc_error, dqmc_eye, dqmc_scalecol, dqmc_scalerow, dqmc_seqmultb, dqmc_seqmultbi, dqmc_trans
dqmc_scalecol calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_eye, dqmc_getb, dqmc_multb_left, dqmc_udtd
dqmc_seqmultbi calls dqmc_eye, dqmc_getbi, dqmc_multbi_left, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_getbi calls dqmc_multbi_right, dqmc_scalecolinv
dqmc_multb_left calls blas_dgemm, dqmc_error, dqmc_scalerow, blas_dscal, dexp, lapack_dsyev
dqmc_multbi_left calls blas_dgemm, dqmc_error, blas_dscal, dexp, lapack_dsyev, dqmc_scalerowinv
dqmc_udtd calls blas_dcopy, dqmc_error, dqmc_scalecol, blas_dscal, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr
dqmc_multb_right calls blas_dgemm, dqmc_error, dqmc_scalecol, blas_dscal, dexp, lapack_dsyev
dqmc_multbi_right calls blas_dgemm, dqmc_error, blas_dscal, dexp, lapack_dsyev, dqmc_scalecolinv
dqmc_scalecolinv calls dscal
dqmc_scalerowinv calls dscal
dqmc_makegtau calls dqmc_getgtau