DQMC_ApplyUpdate – Quest
DQMC_ApplyUpdate Subroutine
10 statements
Source File
public subroutine DQMC_ApplyUpdate(G, forced)
Arguments
Type Intent Optional Attributes Name
type(G_fun), intent(inout) :: G
logical, intent(in) :: forced
Calls
Called by
Call graph
dqmc_applyupdate calls blas_dgemm
dqmc_hub_sweep calls dqmc_applyupdate, dqmc_updateg
dqmc_hub_sweep_cont calls dqmc_applyupdate, dqmc_updateg
dqmc_updateg calls dqmc_applyupdate
dqmc_comp_2dperl calls dqmc_hub_sweep
dqmc_hub_run calls dqmc_hub_sweep
dqmc_ggeom calls dqmc_hub_sweep
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_run