DQMC_Error – Quest
DQMC_Error Subroutine
8 statements
Source File
public subroutine DQMC_Error(message, no)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
integer, intent(in) :: no
Called by
Call graph
dqmc_b_expinit calls dqmc_error
dqmc_ccs_compress calls dqmc_error
dqmc_computeg calls dqmc_error, dqmc_seqmultb
dqmc_config_geti calls dqmc_error
dqmc_config_getpi calls dqmc_error
dqmc_config_getpr calls dqmc_error
dqmc_config_getr calls dqmc_error
dqmc_config_gets calls dqmc_error
dqmc_config_isset calls dqmc_error
dqmc_config_seti calls dqmc_error
dqmc_config_setpi calls dqmc_error
dqmc_config_setpr calls dqmc_error
dqmc_config_setr calls dqmc_error
dqmc_config_sets calls dqmc_error
dqmc_geom_fill calls dqmc_error, construct_hamilt, init_recip_latt
dqmc_geom_read_def calls dqmc_error, dqmc_ccs_compress
dqmc_getgtau calls dqmc_error, dqmc_seqmultb, dqmc_seqmultbi
dqmc_gtau_init calls dqmc_error
dqmc_hub_config calls dqmc_error, dqmc_config_isset, dqmc_hub_init, cfg_get, cfg_set
dqmc_hub_init calls dqmc_error, dqmc_hub_input_hsf, dqmc_b_init, dqmc_getg
dqmc_hub_input_hsf calls dqmc_error
dqmc_multb_left calls dqmc_error
dqmc_multb_right calls dqmc_error
dqmc_multbi_left calls dqmc_error
dqmc_multbi_right calls dqmc_error
dqmc_phy0_avg calls dqmc_error
dqmc_read_config calls dqmc_error
dqmc_udtd calls dqmc_error
cfg_get calls dqmc_config_geti, dqmc_config_getpi, dqmc_config_getpr, dqmc_config_getr, dqmc_config_gets
cfg_set calls dqmc_config_seti, dqmc_config_setpi, dqmc_config_setpr, dqmc_config_setr, dqmc_config_sets
dqmc_b_init calls dqmc_b_expinit
dqmc_change_gtau_time calls dqmc_multb_left, dqmc_multb_right, dqmc_multbi_left, dqmc_multbi_right
dqmc_comp_2dperl calls dqmc_phy0_avg, dqmc_read_config, cfg_get, dqmc_hub_config, dqmc_init_2dperl, dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_geom_init calls dqmc_ccs_compress, cfg_set
dqmc_getb calls dqmc_multb_right
dqmc_getbi calls dqmc_multbi_right
dqmc_getg calls dqmc_computeg, dqmc_multb_left, dqmc_multbi_right
dqmc_gtau_loada calls dqmc_multb_right, dqmc_getb
dqmc_hol_sweep3_cont calls dqmc_computeg
dqmc_hub_run calls dqmc_phy0_avg, dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_hub_sweep2_cont calls dqmc_computeg
dqmc_init_2dperl calls dqmc_ccs_compress
dqmc_makegtau calls dqmc_getgtau, dqmc_change_gtau_time
dqmc_seqmultb calls dqmc_multb_left, dqmc_udtd, dqmc_getb
dqmc_seqmultbi calls dqmc_multbi_left, dqmc_udtd, dqmc_getbi
dqmc_ggeom calls dqmc_geom_fill, dqmc_geom_read_def, dqmc_gtau_init, dqmc_hub_input_hsf, dqmc_phy0_avg, dqmc_read_config, cfg_get, dqmc_geom_init, dqmc_gtau_loada, dqmc_hub_config, dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_tdm1_meas, dqmc_tdm1_meas_para, dqmc_tdm1_selfenergy
dqmc_verify calls dqmc_hub_init, dqmc_hub_run, dqmc_init_2dperl
construct_hamilt calls cfg_get
dqmc_gtau_getg0 calls dqmc_getb
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_tdm1_meas calls dqmc_change_gtau_time
dqmc_tdm1_meas_para calls dqmc_change_gtau_time
init_recip_latt calls cfg_get
dqmc_test calls dqmc_comp_2dperl
dqmc_tdm1_selfenergy calls dqmc_gtau_getg0