DQMC_SeqMultB – Quest
DQMC_SeqMultB Subroutine
46 statements
Source File
public subroutine DQMC_SeqMultB(il, ir, SB, V)
Initially, Q = B_{i} = V_i*B
T = I, T will be the R-factor of the QDR factorization Compute the index of B_{i} The UDT decomposition is performed at every nOrth step, and at the last step. In other steps, we just multiply B_i to the Q-factor multiply B_i to the Q-factor
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: il
integer, intent(in) :: ir
type(SeqB), intent(inout) :: SB
real(kind=wp), intent(in) :: V(SB%n,SB%L)
Calls
Called by
Call graph
dqmc_seqmultb calls dqmc_eye, dqmc_getb, dqmc_multb_left, dqmc_udtd
dqmc_getb calls dqmc_multb_right, dqmc_scalerow
dqmc_multb_left calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalerow
dqmc_udtd calls blas_dcopy, blas_dscal, blas_dtrmm, lapack_dgeqp3, lapack_dorgqr, dqmc_error, dqmc_scalecol
dqmc_multb_right calls blas_dgemm, blas_dscal, dexp, lapack_dsyev, dqmc_error, dqmc_scalecol
dqmc_scalecol calls dscal
dqmc_scalerow calls dscal
dqmc_computeg calls dqmc_seqmultb
dqmc_getgtau calls dqmc_seqmultb
dqmc_getg calls dqmc_computeg
dqmc_hol_sweep3_cont calls dqmc_computeg
dqmc_hub_sweep2_cont calls dqmc_computeg
dqmc_makegtau calls dqmc_getgtau
dqmc_hub_init calls dqmc_getg
dqmc_hub_meas calls dqmc_getg
dqmc_hub_sweep calls dqmc_getg
dqmc_hub_sweep2 calls dqmc_getg
dqmc_hub_sweep_cont calls dqmc_getg
dqmc_comp_2dperl calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_ggeom calls dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_verify calls dqmc_hub_init, dqmc_hub_run
dqmc_test calls dqmc_comp_2dperl