DQMC_Hub_FullMeas – Quest
DQMC_Hub_FullMeas Subroutine
43 statements
Source File
public subroutine DQMC_Hub_FullMeas(Hub, nnb, A_up, A_dn, sgn_up, sgn_dn)
Arguments
Type Intent Optional Attributes Name
type(Hubbard), intent(inout) :: Hub
integer, intent(in) :: nnb
real(kind=wp), intent(in) :: A_up(nnb,nnb)
real(kind=wp), intent(in) :: A_dn(nnb,nnb)
real(kind=wp), intent(in) :: sgn_up
real(kind=wp), intent(in) :: sgn_dn
Calls
Called by
Call graph
dqmc_hub_fullmeas calls dqmc_getg_2nd_order, dqmc_gfun_clone, dqmc_gfun_copyup, dqmc_gfun_duplicate, dqmc_gfun_free, dqmc_phy0_meas, dqmc_phy2_meas
dqmc_phy0_meas calls blas_daxpy, blas_dgemm
dqmc_phy2_meas calls blas_daxpy, dqmc_phy2_pair
dqmc_ggeom calls dqmc_hub_fullmeas