get_inverse – Quest
get_inverse Subroutine
16 statements
Source File
public subroutine get_inverse(a, inv)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a(3,3)
real(kind=wp), intent(out) :: inv(3,3)
Called by
Call graph
assign_phase calls get_inverse
construct_lattice calls get_inverse
construct_recip_lattice calls get_inverse
dqmc_init_kmate calls get_inverse
hoptowho calls get_inverse
init_lattice calls get_inverse
init_recip_latt calls get_inverse
map_symm_bonds calls get_inverse, hoptowho
map_symm_lattice calls get_inverse
map_symm_recip_lattice calls get_inverse
construct_hamilt calls hoptowho
construct_pairs calls hoptowho
dqmc_geom_fill calls assign_phase, construct_lattice, construct_recip_lattice, init_lattice, init_recip_latt, map_symm_bonds, map_symm_lattice, map_symm_recip_lattice, construct_hamilt, construct_pairs
dqmc_ggeom calls dqmc_geom_fill