init_recip_latt – Quest
init_recip_latt Subroutine
57 statements
Source File
public subroutine init_recip_latt(lattice, recip_lattice, applytwist, cfg)
Arguments
Type Intent Optional Attributes Name
type(lattice_t), intent(in), target :: lattice
type(recip_lattice_t), intent(out), target :: recip_lattice
logical, intent(in) :: applytwist
type(config), intent(in), target :: cfg
Calls
Called by
Call graph
init_recip_latt calls cfg_get, get_inverse
cfg_get calls dqmc_config_geti, dqmc_config_getpi, dqmc_config_getpr, dqmc_config_getr, dqmc_config_gets
dqmc_config_geti calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpi calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_gets calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_geom_fill calls init_recip_latt
dqmc_ggeom calls dqmc_geom_fill