init_lattice – Quest
init_lattice Subroutine
80 statements
Source File
public subroutine init_lattice(lattice, SOP)
Arguments
Type Intent Optional Attributes Name
type(lattice_t), target :: lattice
integer, intent(in) :: SOP
Calls
Called by
Call graph
init_lattice calls convert_to_fractional, count_atom, get_det, get_inverse, move_to_record
count_atom calls move_to_record
dqmc_geom_fill calls init_lattice
dqmc_ggeom calls dqmc_geom_fill