map_symm_lattice – Quest
map_symm_lattice Subroutine
145 statements
Source File
public subroutine map_symm_lattice(SymmOp, lattice, hamilt, SOP)
Uses
DQMC_HAMILT
DQMC_LATT
Arguments
Type Intent Optional Attributes Name
type(symm_operations) :: SymmOp
type(lattice_t), intent(in) :: lattice
type(Hamiltonian_t), intent(in) :: hamilt
integer, intent(in) :: SOP
Calls
Called by
Call graph
map_symm_lattice calls apply_point_symm, get_inverse
dqmc_geom_fill calls map_symm_lattice
dqmc_ggeom calls dqmc_geom_fill