move_to_record – Quest
move_to_record Function
18 statements
Source File
public function move_to_record(string, iunit)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
integer, intent(in) :: iunit
Return Value logical
Called by
Call graph
assign_phase calls move_to_record
construct_hamilt calls move_to_record
construct_pairs calls move_to_record
count_atom calls move_to_record
count_symmetry calls move_to_record
init_lattice calls move_to_record, count_atom
read_bonds calls move_to_record
read_symm calls move_to_record, count_symmetry
dqmc_geom_fill calls assign_phase, construct_hamilt, construct_pairs, init_lattice, read_bonds, read_symm
dqmc_ggeom calls dqmc_geom_fill