QUEST_GG_Init – Quest
QUEST_GG_Init Subroutine
60 statements
Source File
public subroutine QUEST_GG_Init(S, prefix)
Arguments
Type Intent Optional Attributes Name
type(Struct), intent(inout) :: S
character(len=*), intent(in) :: prefix
Calls
Call graph
quest_gg_init calls mumap, quest_read_adj, quest_read_class, quest_read_phase, umap
quest_read_adj calls bs
quest_read_class calls label