ran0 – Quest
ran0 Subroutine
8 statements
Source File
public subroutine ran0(n, var, seed)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(out) :: var(n)
integer, intent(inout) :: seed(4)
Calls
Called by
Call graph
ran0 calls dlarnv
dqmc_comp_2dperl calls ran0, dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hol_sweep3_cont calls ran0
dqmc_hub_init calls ran0
dqmc_hub_meas calls ran0
dqmc_hub_sweep calls ran0
dqmc_hub_sweep2 calls ran0
dqmc_hub_sweep2_cont calls ran0
dqmc_hub_sweep_cont calls ran0
intran calls ran0
dqmc_ggeom calls ran0, dqmc_hub_meas, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_hub_config
dqmc_hub_config calls dqmc_hub_init
dqmc_hub_run calls dqmc_hub_sweep, dqmc_hub_sweep2
dqmc_test calls dqmc_comp_2dperl
dqmc_verify calls dqmc_hub_init, dqmc_hub_run