ran1 – Quest
ran1 Subroutine
8 statements
Source File
public subroutine ran1(n, var, seed)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(out) :: var(n)
integer, intent(inout) :: seed(4)
Calls
Called by
Call graph
ran1 calls dlarnv
dqmc_hub_init calls ran1
dqmc_hub_config calls dqmc_hub_init
dqmc_verify calls dqmc_hub_init
dqmc_comp_2dperl calls dqmc_hub_config
dqmc_ggeom calls dqmc_hub_config
dqmc_test calls dqmc_comp_2dperl