dqmc_verify – Quest
dqmc_verify Program
141 statements
Source File
Uses
DQMC_2DPERL
DQMC_MPI
DQMC_Hubbard
DQMC_STRUCT
DQMC_Phy0
Calls
Variables
Type Attributes Name Initial
integer, parameter :: nx = 4
integer, parameter :: ny = 4
integer, parameter :: N = nx*ny
real(kind=wp), parameter :: t(4) = [0.3_wp, 0.6_wp, ONE, ZERO]
real(kind=wp), parameter :: dtau = 0.125_wp
real(kind=wp), parameter :: U(6) = [ONE, TWO, TWO*TWO, ZERO, -ONE, -TWO]
real(kind=wp), parameter :: mu(3) = [HALF, ZERO, -HALF]
integer, parameter :: L = 12
integer, parameter :: HSF_IPT = -1
integer, parameter :: n_t = 1
integer, parameter :: nWarm = 1000
integer, parameter :: nPass = 5000
integer, parameter :: nTry = 0
integer, parameter :: nmeas = 12
integer, parameter :: nBin = 10
integer, parameter :: tausk = 10
integer, parameter :: idum = 0
integer, parameter :: nOrth = 12
integer, parameter :: nWrap = 12
integer, parameter :: ssxx = 0
integer, parameter :: fixw = 0
real(kind=wp), parameter :: errrate = 0.001_wp
real(kind=wp), parameter :: difflim = 0.001_wp
character(len=*), parameter :: FMT_CMP = "(a20,f10.6,'|',f10.6,' +-',f10.6,'|',f6.2,' :',f6.2)"
character(len=*), parameter :: FMT_CONFIG = "('Parameters : ',4(a,' =',f6.2,', '))"
character(len=*), parameter :: FMT_TITLE = "(20X,'Theoretical | Computed (avg +- error) ||T-C| : error')"
real(kind=wp) :: t_up(4)
real(kind=wp) :: t_dn(4)
real(kind=wp) :: mu_up(3)
real(kind=wp) :: mu_dn(3)
type(Hubbard) :: Hub
integer :: i
integer :: j
integer :: k
real(kind=wp) :: rho
real(kind=wp) :: energy_total
real(kind=wp) :: avg
real(kind=wp) :: err
real(kind=wp) :: one_site_occupancy
real(kind=wp) :: tmp1
real(kind=wp) :: tmp2
real(kind=wp) :: tmp3
real(kind=wp) :: beta
real(kind=wp) :: lambda(N)
real(kind=wp) :: X(N)
real :: t1
real :: t2
character(len=30) :: name
integer :: cnt(0:3)
Subroutines
subroutine Display(name, theo, avg, err)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
real(kind=wp), intent(in) :: theo
real(kind=wp), intent(in) :: avg
real(kind=wp), intent(in) :: err
subroutine DQMC_Phy0_GetResult(P0, meas, name, avg, err)
Arguments
Type Intent Optional Attributes Name
type(Phy0), intent(in) :: P0
integer, intent(in) :: meas
character(len=*), intent(inout) :: name
real(kind=wp), intent(inout) :: avg
real(kind=wp), intent(inout) :: err
Call graph
dqmc_verify calls display, dqmc_hub_free, dqmc_hub_init, dqmc_hub_run, dqmc_init_2dperl, dqmc_mpi_init, dqmc_phy0_getresult
dqmc_hub_free calls dqmc_b_free, dqmc_gfun_free, dqmc_phy0_free, dqmc_phy2_free, dqmc_seqb_free, dqmc_struct_free, dqmc_wspace_free
dqmc_hub_init calls dqmc_b_init, dqmc_error, dqmc_getg, dqmc_gfun_clone, dqmc_gfun_init, dqmc_hub_init_vmat, dqmc_hub_input_hsf, dqmc_phy0_init, dqmc_phy2_init, dqmc_seqb_init, dqmc_warning, dqmc_wspace_allocate, ran0, ran1
dqmc_hub_run calls dqmc_phy2_avg, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_phy0_avg, dqmc_phy0_geterr, dqmc_phy2_geterr
dqmc_init_2dperl calls dqmc_2dperl_dc_imp1, dqmc_2dperl_dc_imp2, dqmc_ccs_compress
dqmc_phy2_avg calls dqmc_phy2_avg_symm, dqmc_phy2_avg_wave
dqmc_b_init calls dqmc_b_expinit
dqmc_ccs_compress calls dqmc_error
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
dqmc_hub_input_hsf calls dqmc_error
dqmc_hub_sweep calls dqmc_getg, ran0, dqmc_applyupdate, dqmc_getg_2nd_order, dqmc_gfun_copyup, dqmc_gfun_getjj, dqmc_phy0_meas, dqmc_phy2_meas, dqmc_syncwraps, dqmc_updateg, dqmc_updatewraps
dqmc_hub_sweep2 calls dqmc_getg, ran0, dqmc_gfun_copyup
dqmc_phy0_avg calls dqmc_error, blas_dscal
dqmc_phy0_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_phy2_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_struct_free calls dqmc_ccs_free
dqmc_wspace_allocate calls lapack_dgeqp3, lapack_dgetri, lapack_dorgqr, lapack_dormqr, lapack_dsyev
ran0 calls dlarnv
ran1 calls dlarnv
dqmc_jackknife calls dqmc_jackknife_complex, dqmc_jackknife_real
dqmc_signjackknife calls dqmc_signjackknife_complex, dqmc_signjackknife_real
dqmc_applyupdate calls blas_dgemm
dqmc_b_expinit calls dqmc_error, blas_dscal, lapack_dsyev, blas_dgemm, dexp
dqmc_computeg calls dqmc_error, dqmc_warning, blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_scalerow, dqmc_seqmultb, dqmc_trans
dqmc_gfun_getjj calls blas_ddot
dqmc_multb_left calls dqmc_error, blas_dscal, lapack_dsyev, blas_dgemm, dexp, dqmc_scalerow
dqmc_multbi_right calls dqmc_error, blas_dscal, lapack_dsyev, blas_dgemm, dexp, dqmc_scalecolinv
dqmc_phy0_meas calls blas_daxpy, blas_dgemm
dqmc_phy2_avg_symm calls dqmc_pair_symm
dqmc_phy2_avg_wave calls dqmc_wave_avg
dqmc_phy2_meas calls blas_daxpy, dqmc_phy2_pair
dqmc_updateg calls blas_dscal, dqmc_applyupdate, blas_dgemv
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_multb_left, dqmc_eye, dqmc_getb, dqmc_udtd
dqmc_wave_avg calls blas_ddot, blas_dgemm
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_udtd calls dqmc_error, blas_dcopy, blas_dscal, lapack_dgeqp3, lapack_dorgqr, blas_dtrmm, dqmc_scalecol
dqmc_multb_right calls dqmc_error, blas_dscal, lapack_dsyev, blas_dgemm, dexp, dqmc_scalecol
dqmc_scalecol calls dscal