dqmc_test – Quest
dqmc_test Program
11 statements
Source File
Uses
DQMC_MPI
DQMC_2DPERL
Calls
Variables
Type Attributes Name Initial
integer :: t1
integer :: t2
integer :: rate
Call graph
dqmc_test calls dqmc_comp_2dperl, dqmc_mpi_init
dqmc_comp_2dperl calls cfg_get, dqmc_phy2_avg, dqmc_config_free, dqmc_hub_config, dqmc_hub_free, dqmc_hub_meas, dqmc_hub_print, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_init_2dperl, dqmc_open_file, dqmc_phy0_avg, dqmc_phy0_geterr, dqmc_phy2_geterr, dqmc_read_config, ran0
cfg_get calls dqmc_config_geti, dqmc_config_getpi, dqmc_config_getpr, dqmc_config_getr, dqmc_config_gets
dqmc_phy2_avg calls dqmc_phy2_avg_symm, dqmc_phy2_avg_wave
dqmc_hub_config calls cfg_get, cfg_set, dqmc_config_isset, dqmc_hub_init, dqmc_warning
dqmc_hub_free calls dqmc_b_free, dqmc_gfun_free, dqmc_phy0_free, dqmc_phy2_free, dqmc_seqb_free, dqmc_struct_free, dqmc_wspace_free
dqmc_hub_meas calls ran0, dqmc_getg, dqmc_getg_2nd_order, dqmc_gfun_clone, dqmc_gfun_copyup, dqmc_gfun_duplicate, dqmc_gfun_free, dqmc_phy0_meas, dqmc_phy2_meas
dqmc_hub_print calls dqmc_hub_outputparam, dqmc_phy0_print, dqmc_phy2_print
dqmc_hub_sweep calls ran0, dqmc_applyupdate, dqmc_getg, dqmc_getg_2nd_order, dqmc_gfun_copyup, dqmc_gfun_getjj, dqmc_phy0_meas, dqmc_phy2_meas, dqmc_syncwraps, dqmc_updateg, dqmc_updatewraps
dqmc_hub_sweep2 calls ran0, dqmc_getg, dqmc_gfun_copyup
dqmc_init_2dperl calls dqmc_2dperl_dc_imp1, dqmc_2dperl_dc_imp2, dqmc_ccs_compress
dqmc_phy0_avg calls blas_dscal, dqmc_error
dqmc_phy0_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_phy2_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_read_config calls dqmc_open_file, dqmc_default_def, dqmc_error, dqmc_find_param, dqmc_read_def, dqmc_warning
ran0 calls dlarnv
cfg_set calls dqmc_config_seti, dqmc_config_setpi, dqmc_config_setpr, dqmc_config_setr, dqmc_config_sets
dqmc_jackknife calls dqmc_jackknife_complex, dqmc_jackknife_real
dqmc_signjackknife calls dqmc_signjackknife_complex, dqmc_signjackknife_real
dqmc_applyupdate calls blas_dgemm
dqmc_ccs_compress calls dqmc_error
dqmc_config_geti calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpi calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_gets calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_isset calls dqmc_error, dqmc_find_param
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
dqmc_gfun_getjj calls blas_ddot
dqmc_hub_init calls ran0, dqmc_error, dqmc_getg, dqmc_gfun_clone, dqmc_warning, dqmc_b_init, dqmc_gfun_init, dqmc_hub_init_vmat, dqmc_hub_input_hsf, dqmc_phy0_init, dqmc_phy2_init, dqmc_seqb_init, dqmc_wspace_allocate, ran1
dqmc_hub_outputparam calls dqmc_warning, dqmc_hub_output_hsf
dqmc_phy0_meas calls blas_daxpy, blas_dgemm
dqmc_phy0_print calls dqmc_print_realarray
dqmc_phy2_avg_symm calls dqmc_pair_symm
dqmc_phy2_avg_wave calls dqmc_wave_avg
dqmc_phy2_meas calls blas_daxpy, dqmc_phy2_pair
dqmc_phy2_print calls dqmc_print_realarray
dqmc_read_def calls dqmc_readln
dqmc_struct_free calls dqmc_ccs_free
dqmc_updateg calls blas_dscal, dqmc_applyupdate, blas_dgemv
dqmc_b_init calls dqmc_b_expinit
dqmc_computeg calls dqmc_error, dqmc_warning, blas_dcopy, lapack_dgetrf, lapack_dgetrs, dqmc_scalerow, dqmc_seqmultb, dqmc_trans
dqmc_config_seti calls dqmc_error, dqmc_find_param
dqmc_config_setpi calls dqmc_error, dqmc_find_param
dqmc_config_setpr calls dqmc_error, dqmc_find_param
dqmc_config_setr calls dqmc_error, dqmc_find_param
dqmc_config_sets calls dqmc_error, dqmc_find_param
dqmc_hub_input_hsf calls dqmc_error
dqmc_multb_left calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalerow
dqmc_multbi_right calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalecolinv
dqmc_wave_avg calls blas_ddot, blas_dgemm
dqmc_wspace_allocate calls lapack_dgeqp3, lapack_dgetri, lapack_dorgqr, lapack_dormqr, lapack_dsyev
ran1 calls dlarnv
dqmc_b_expinit calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev
dqmc_scalecolinv calls dscal
dqmc_scalerow calls dscal
dqmc_seqmultb calls dqmc_multb_left, dqmc_eye, dqmc_getb, dqmc_udtd
dqmc_getb calls dqmc_scalerow, dqmc_multb_right
dqmc_udtd calls blas_dscal, dqmc_error, blas_dcopy, lapack_dgeqp3, lapack_dorgqr, blas_dtrmm, dqmc_scalecol
dqmc_multb_right calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalecol
dqmc_scalecol calls dscal