dqmc_ggeom – Quest
dqmc_ggeom Program
193 statements
Source File
Uses
DQMC_MPI
DQMC_TDM1
DQMC_GEOM_WRAP
DQMC_Hubbard
DQMC_Cfg
DQMC_OMP
Calls
Variables
Type Attributes Name Initial
integer :: t1
integer :: t2
integer :: rate
type(config) :: cfg
type(Hubbard) :: Hub
type(GeomWrap) :: Gwrap
type(TDM1) :: tm
type(Gtau) :: tau
type(TDM1), pointer :: ptm(:)
type(Gtau), pointer :: ptau(:)
character(len=slen) :: gfile
logical :: tformat
integer :: na
integer :: nt
integer :: nkt
integer :: nkg
integer :: i
integer :: j
integer :: k
integer :: slice
integer :: nhist
integer :: comp_tdm
integer :: nBin
integer :: nIter
character(len=60) :: ofile
integer :: OPT
integer :: symmetries_output_file_unit
integer :: FLD_UNIT
integer :: TDM_UNIT
real(kind=wp) :: randn(1)
integer :: nproc
Call graph
dqmc_ggeom calls cfg_get, dqmc_phy2_avg, dqmc_phy2_getirrep, dqmc_config_free, dqmc_count_records, dqmc_geom_fill, dqmc_geom_init, dqmc_geom_print, dqmc_geom_read_def, dqmc_gtau_init, dqmc_gtau_loada, dqmc_hub_config, dqmc_hub_free, dqmc_hub_fullmeas, dqmc_hub_init_vmat, dqmc_hub_input_hsf, dqmc_hub_meas, dqmc_hub_outputparam, dqmc_hub_sweep, dqmc_hub_sweep2, dqmc_mpi_final, dqmc_mpi_init, dqmc_omp_init, dqmc_open_file, dqmc_phy0_avg, dqmc_phy0_geterr, dqmc_phy0_geterrft, dqmc_phy0_getft, dqmc_phy0_print, dqmc_phy0_printft, dqmc_phy2_geterr, dqmc_phy2_geterrirrep, dqmc_phy2_print, dqmc_phy2_printsymm, dqmc_phy2_wavesymm, dqmc_print_headerft, dqmc_read_config, dqmc_tdm1_avg, dqmc_tdm1_free, dqmc_tdm1_geterr, dqmc_tdm1_geterrkft, dqmc_tdm1_getkft, dqmc_tdm1_init, dqmc_tdm1_meas, dqmc_tdm1_meas_para, dqmc_tdm1_print, dqmc_tdm1_printkft, dqmc_tdm1_selfenergy, ran0
cfg_get calls dqmc_config_geti, dqmc_config_getpi, dqmc_config_getpr, dqmc_config_getr, dqmc_config_gets
dqmc_phy2_avg calls dqmc_phy2_avg_symm, dqmc_phy2_avg_wave
dqmc_phy2_getirrep calls dqmc_phy2_getirrep_connected, dqmc_phy2_getirrep_full
dqmc_geom_fill calls analyze_input, assign_gf_phase, assign_phase, construct_bond_classes, construct_hamilt, construct_lattice, construct_lattice_classes, construct_pair_classes, construct_pairs, construct_recip_lattice, construct_recip_lattice_classes, count_hop_class, count_local_classes, dqmc_error, dqmc_fill_fourierc, init_lattice, init_recip_latt, map_symm_bonds, map_symm_lattice, map_symm_pairs, map_symm_recip_lattice, read_bonds, read_symm
dqmc_geom_init calls cfg_set, dqmc_ccs_compress, group_hopping
dqmc_geom_print calls dqmc_ccs_print
dqmc_geom_read_def calls dqmc_ccs_compress, dqmc_error, dqmc_geom_discover_f, dqmc_geom_discover_map, dqmc_readln, dqmc_warning
dqmc_gtau_init calls lapack_dgetri, dqmc_error
dqmc_gtau_loada calls lapack_dgetrf, lapack_dgetri, dqmc_getb, dqmc_gtau_setalias, dqmc_multb_right
dqmc_hub_config calls cfg_get, cfg_set, dqmc_config_isset, dqmc_hub_init, dqmc_warning
dqmc_hub_free calls dqmc_b_free, dqmc_gfun_free, dqmc_phy0_free, dqmc_phy2_free, dqmc_seqb_free, dqmc_struct_free, dqmc_wspace_free
dqmc_hub_fullmeas calls dqmc_getg_2nd_order, dqmc_gfun_clone, dqmc_gfun_copyup, dqmc_gfun_duplicate, dqmc_gfun_free, dqmc_phy0_meas, dqmc_phy2_meas
dqmc_hub_input_hsf calls dqmc_error
dqmc_hub_meas calls ran0, dqmc_getg, dqmc_getg_2nd_order, dqmc_gfun_clone, dqmc_gfun_copyup, dqmc_gfun_duplicate, dqmc_gfun_free, dqmc_phy0_meas, dqmc_phy2_meas
dqmc_hub_outputparam calls dqmc_hub_output_hsf, dqmc_warning
dqmc_hub_sweep calls ran0, dqmc_applyupdate, dqmc_getg, dqmc_getg_2nd_order, dqmc_gfun_copyup, dqmc_gfun_getjj, dqmc_phy0_meas, dqmc_phy2_meas, dqmc_syncwraps, dqmc_updateg, dqmc_updatewraps
dqmc_hub_sweep2 calls ran0, dqmc_getg, dqmc_gfun_copyup
dqmc_omp_init calls omp_set_num_threads
dqmc_phy0_avg calls blas_dscal, dqmc_error
dqmc_phy0_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_phy0_getft calls dconjg, zgemm, zheev
dqmc_phy0_print calls dqmc_print_realarray
dqmc_phy0_printft calls dqmc_print_eigenmode, dqmc_print_realarray
dqmc_phy2_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_phy2_geterrirrep calls dqmc_phy2_pair, dqmc_wave_avg
dqmc_phy2_print calls dqmc_print_realarray
dqmc_read_config calls dqmc_open_file, dqmc_default_def, dqmc_error, dqmc_find_param, dqmc_read_def, dqmc_warning
dqmc_tdm1_avg calls dscal
dqmc_tdm1_geterr calls dqmc_jackknife, dqmc_signjackknife
dqmc_tdm1_getkft calls dqmc_getftk
dqmc_tdm1_init calls dqmc_tdm1_initftw, dqmc_tdm1_initprop
dqmc_tdm1_meas calls dqmc_change_gtau_time, dqmc_gtau_copyup, dqmc_gtau_dumpa, dqmc_tdm1_compute
dqmc_tdm1_meas_para calls dqmc_change_gtau_time, dqmc_gtau_copyup, dqmc_gtau_dumpa, dqmc_tdm1_compute
dqmc_tdm1_print calls dqmc_print_array
dqmc_tdm1_printkft calls dqmc_print_array
dqmc_tdm1_selfenergy calls dqmc_print_array, dqmc_getftk, dqmc_gtau_getg0, zgemv, zgetrf, zgetri
ran0 calls dlarnv
cfg_set calls dqmc_config_seti, dqmc_config_setpi, dqmc_config_setpr, dqmc_config_setr, dqmc_config_sets
dqmc_jackknife calls dqmc_jackknife_complex, dqmc_jackknife_real
dqmc_print_array calls dqmc_print_realarray, dqmc_print_complexarray
dqmc_signjackknife calls dqmc_signjackknife_complex, dqmc_signjackknife_real
assign_phase calls convert_to_fractional, get_det, get_inverse, move_to_record
construct_hamilt calls cfg_get, dqmc_hamilt_groupckb, find_neighbors, hoptowho, move_to_record
construct_lattice calls get_inverse
construct_pairs calls hoptowho, move_to_record
construct_recip_lattice calls closer_to_zero, get_inverse
dqmc_applyupdate calls blas_dgemm
dqmc_ccs_compress calls dqmc_error
dqmc_change_gtau_time calls dqmc_gtau_setalias, dqmc_multb_right, dqmc_multb_left, dqmc_multbi_left, dqmc_multbi_right
dqmc_config_geti calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpi calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getpr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_getr calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_gets calls dqmc_error, dqmc_find_param, dqmc_warning
dqmc_config_isset calls dqmc_error, dqmc_find_param
dqmc_getb calls dqmc_multb_right, dqmc_scalerow
dqmc_getftk calls dconjg
dqmc_getg calls blas_dcopy, dqmc_computeg, dqmc_matdiff, dqmc_multb_left, dqmc_multbi_right
dqmc_gfun_getjj calls blas_ddot
dqmc_gtau_dumpa calls dqmc_gtau_setalias
dqmc_gtau_getg0 calls dqmc_getb, dcopy, dgemm, dsyev, dqmc_scalecol
dqmc_hub_init calls dqmc_hub_init_vmat, dqmc_hub_input_hsf, ran0, dqmc_error, dqmc_getg, dqmc_gfun_clone, dqmc_warning, dqmc_b_init, dqmc_gfun_init, dqmc_phy0_init, dqmc_phy2_init, dqmc_seqb_init, dqmc_wspace_allocate, ran1
dqmc_multb_right calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalecol
dqmc_phy0_meas calls blas_daxpy, blas_dgemm
dqmc_phy2_avg_symm calls dqmc_pair_symm
dqmc_phy2_avg_wave calls dqmc_wave_avg
dqmc_phy2_getirrep_connected calls dqmc_phy2_pair, lapack_dsyev
dqmc_phy2_getirrep_full calls lapack_dsyev
dqmc_phy2_meas calls dqmc_phy2_pair, blas_daxpy
dqmc_read_def calls dqmc_readln
dqmc_struct_free calls dqmc_ccs_free
dqmc_updateg calls blas_dscal, dqmc_applyupdate, blas_dgemv
dqmc_wave_avg calls blas_ddot, blas_dgemm
init_lattice calls convert_to_fractional, count_atom, get_det, get_inverse, move_to_record
init_recip_latt calls cfg_get, get_inverse
map_symm_bonds calls get_inverse, hoptowho
map_symm_lattice calls apply_point_symm, get_inverse
map_symm_recip_lattice calls apply_point_symm, get_inverse
read_bonds calls move_to_record
read_symm calls count_symmetry, move_to_record
count_atom calls move_to_record
count_symmetry calls move_to_record
dqmc_b_init calls dqmc_b_expinit
dqmc_computeg calls lapack_dgetrf, dqmc_error, dqmc_warning, blas_dcopy, dqmc_scalerow, lapack_dgetrs, dqmc_seqmultb, dqmc_trans
dqmc_config_seti calls dqmc_error, dqmc_find_param
dqmc_config_setpi calls dqmc_error, dqmc_find_param
dqmc_config_setpr calls dqmc_error, dqmc_find_param
dqmc_config_setr calls dqmc_error, dqmc_find_param
dqmc_config_sets calls dqmc_error, dqmc_find_param
dqmc_multb_left calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalerow
dqmc_multbi_left calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalerowinv
dqmc_multbi_right calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev, dqmc_scalecolinv
dqmc_scalecol calls dscal
dqmc_scalerow calls dscal
dqmc_wspace_allocate calls lapack_dgetri, lapack_dsyev, lapack_dgeqp3, lapack_dorgqr, lapack_dormqr
hoptowho calls get_inverse
ran1 calls dlarnv
dqmc_b_expinit calls blas_dscal, dqmc_error, blas_dgemm, dexp, lapack_dsyev
dqmc_scalecolinv calls dscal
dqmc_scalerowinv calls dscal
dqmc_seqmultb calls dqmc_getb, dqmc_multb_left, dqmc_eye, dqmc_udtd
dqmc_udtd calls blas_dscal, dqmc_error, blas_dcopy, dqmc_scalecol, lapack_dgeqp3, lapack_dorgqr, blas_dtrmm